Scroom: Scroom::Utils::Counter Class Reference
Scroom::Utils::Counter Class Reference
#include <utilities.hh>
Public Member Functions
void registerCount (Count::Ptr count)
void unregisterCount (Count::Ptr count)
void dump ()
std::list< Count::Ptr > getCounts ()
Static Public Member Functions
static Counter * instance ()
Private Member Functions
Counter ()
Private Attributes
std::list< Count::Ptr > counts
boost::mutex mut
Detailed Description
Definition at line 94 of file utilities.hh.
Constructor & Destructor Documentation
Counter::Counter () private
Definition at line 52 of file counter.cc.
Referenced by instance().
 {
   g_timeout_add_seconds(10, timedDumpCounts, this);
 }
Member Function Documentation
void Counter::dump ()
Definition at line 69 of file counter.cc.
Referenced by Scroom::Utils::dumpCounts(), and timedDumpCounts().
 {
   boost::unique_lock<boost::mutex> lock(mut);
   printf("%ld", (long)counts.size());
   for(Count::Ptr& c: counts)
   {
     printf(", %s, %ld", c->name.c_str(), c->count);
   }
   printf("\n");
 }
std::list< Count::Ptr > Counter::getCounts ()
Definition at line 80 of file counter.cc.
 {
   boost::unique_lock<boost::mutex> lock(mut);
   return counts;
 }
Counter * Counter::instance () static
Definition at line 46 of file counter.cc.
Referenced by Scroom::Utils::Count::create(), and Scroom::Utils::dumpCounts().
 {
   static Counter* me = new Counter();
   return me;
 }
void Counter::registerCount (Count::Ptr count)
Definition at line 57 of file counter.cc.
Referenced by Scroom::Utils::Count::create().
 {
   boost::unique_lock<boost::mutex> lock(mut);
   counts.push_back(count);
 }
void Counter::unregisterCount (Count::Ptr count)
Definition at line 63 of file counter.cc.
 {
   boost::unique_lock<boost::mutex> lock(mut);
   counts.remove(count);
 }
Member Data Documentation
std::list<Count::Ptr> Scroom::Utils::Counter::counts private
Definition at line 99 of file utilities.hh.
Referenced by dump(), getCounts(), registerCount(), and unregisterCount().
boost::mutex Scroom::Utils::Counter::mut private
Definition at line 100 of file utilities.hh.
Referenced by dump(), getCounts(), registerCount(), and unregisterCount().
The documentation for this class was generated from the following files:
inc/scroom/utilities.hh
libs/util/src/counter.cc