Scroom: ColormapHelperBase Class Reference
ColormapHelperBase Class Reference
#include <colormappable.hh>
Public Types
typedef boost::shared_ptr
< ColormapHelperBase > Ptr
Public Types inherited from ColormapProvider
typedef boost::shared_ptr
< ColormapProvider > Ptr
Public Types inherited from Colormappable
typedef boost::shared_ptr
< Colormappable > Ptr
typedef boost::weak_ptr
< Colormappable > WeakPtr
Public Member Functions
ColormapHelperBase (Colormap::Ptr const &colormap)
virtual void setColormap (Colormap::Ptr colormap)
Request that the presentation use the given colormap.
virtual Colormap::Ptr getOriginalColormap ()
Retrieve the images colormap (if any)
virtual int getNumberOfColors ()
Retrieve the number of colors in use by the presentation.
virtual Color getMonochromeColor ()
virtual void setMonochromeColor (const Color &c)
virtual void setTransparentBackground ()
virtual void disableTransparentBackground ()
virtual bool getTransparentBackground ()
virtual Colormap::Ptr getColormap ()
virtual void setOriginalColormap (Colormap::Ptr colormap)
Public Member Functions inherited from ColormapProvider
virtual ~ColormapProvider ()
Public Member Functions inherited from Colormappable
virtual ~Colormappable ()
Virtual destructor.
Public Attributes
Colormap::Ptr colormap
Colormap::Ptr originalColormap
Private Member Functions
NORETURN void OperationNotSupported ()
Detailed Description
Definition at line 159 of file colormappable.hh.
Member Typedef Documentation
typedef boost::shared_ptr<ColormapHelperBase> ColormapHelperBase::Ptr
Definition at line 162 of file colormappable.hh.
Constructor & Destructor Documentation
ColormapHelperBase::ColormapHelperBase (Colormap::Ptr const & colormap)
Definition at line 14 of file colormap-helpers.cc.
   : colormap(colormap), originalColormap(colormap)
 {
 }
Member Function Documentation
void ColormapHelperBase::disableTransparentBackground () virtual
Implements Colormappable.
Reimplemented in MonochromeColormapHelper.
Definition at line 55 of file colormap-helpers.cc.
 {
   OperationNotSupported();
 }
Colormap::Ptr ColormapHelperBase::getColormap () virtual
Implements ColormapProvider.
Definition at line 65 of file colormap-helpers.cc.
 {
   return colormap;
 }
Color ColormapHelperBase::getMonochromeColor () virtual
Implements Colormappable.
Reimplemented in MonochromeColormapHelper.
Definition at line 39 of file colormap-helpers.cc.
 {
   OperationNotSupported();
 }
int ColormapHelperBase::getNumberOfColors () virtual
Retrieve the number of colors in use by the presentation.
Implements Colormappable.
Definition at line 34 of file colormap-helpers.cc.
 {
   return originalColormap->colors.size();
 }
Colormap::Ptr ColormapHelperBase::getOriginalColormap () virtual
Retrieve the images colormap (if any)
Implements Colormappable.
Definition at line 29 of file colormap-helpers.cc.
 {
   return originalColormap;
 }
bool ColormapHelperBase::getTransparentBackground () virtual
Implements Colormappable.
Reimplemented in MonochromeColormapHelper.
Definition at line 60 of file colormap-helpers.cc.
 {
   OperationNotSupported();
 }
void ColormapHelperBase::OperationNotSupported () private
Definition at line 70 of file colormap-helpers.cc.
Referenced by disableTransparentBackground(), getMonochromeColor(), getTransparentBackground(), setMonochromeColor(), and setTransparentBackground().
 {
   throw std::runtime_error("Operation not supported");
 }
void ColormapHelperBase::setColormap (Colormap::Ptr colormap) virtual
Request that the presentation use the given colormap.
Implements Colormappable.
Definition at line 19 of file colormap-helpers.cc.
 {
   this->colormap = colormap;
 }
void ColormapHelperBase::setMonochromeColor (const Color & c) virtual
Implements Colormappable.
Reimplemented in MonochromeColormapHelper.
Definition at line 44 of file colormap-helpers.cc.
 {
   UNUSED(c);
   OperationNotSupported();
 }
void ColormapHelperBase::setOriginalColormap (Colormap::Ptr colormap) virtual
Definition at line 24 of file colormap-helpers.cc.
 {
   this->originalColormap = colormap;
 }
void ColormapHelperBase::setTransparentBackground () virtual
Implements Colormappable.
Reimplemented in MonochromeColormapHelper.
Definition at line 50 of file colormap-helpers.cc.
 {
   OperationNotSupported();
 }
Member Data Documentation
Colormap::Ptr ColormapHelperBase::colormap
Definition at line 165 of file colormappable.hh.
Referenced by getColormap(), MonochromeColormapHelper::regenerateColormap(), setColormap(), and setOriginalColormap().
Colormap::Ptr ColormapHelperBase::originalColormap
Definition at line 166 of file colormappable.hh.
Referenced by getNumberOfColors(), getOriginalColormap(), and setOriginalColormap().
The documentation for this class was generated from the following files:
inc/scroom/colormappable.hh
libs/scroom/src/colormap-helpers.cc