
# Due to windows docker issues, we can't configure/build in the volume mount.
# As a workaround, we clone the repo to C:\scroom manually
variables:
  GIT_STRATEGY: none

stages:
  - build
  - install

build-windows:
  stage: build
  # This is a windows server core docker image with an msys2 install.
  # It includes all required msys packages
  image: 192.168.2.19:4567/roan/scroom-ci:latest
  tags:
    - Windows
  script:
    - dir
    - if (Test-Path '.\scroom_build') { Remove-Item '.\scroom_build' -Recurse -Force; }
    - dir
    - cd C:\
    - C:/msys64/usr/bin/bash -c "git clone https://gitlab.com/sep-group-2/scroom"
    - dir
    - cd scroom
    - C:/msys64/usr/bin/bash -c "git checkout $CI_COMMIT_SHA"
    - C:/msys64/usr/bin/bash -c "autoreconf -i"
    - C:/msys64/usr/bin/bash -c "./configure --prefix='C:/build'"
    - C:/msys64/usr/bin/bash -c "make 2> /dev/null"
  retry:
    max: 2
    when: runner_system_failure
  artifacts:
    expire_in: 1 day
    paths:
      - scroom/

windows-portable:
  stage: install
  image: image: 192.168.2.19:4567/roan/scroom-ci:latest
  tags:
    - Windows
  script:
    - cd scroom
    - C:/msys64/usr/bin/bash -c "make install-win-portable"
    # Finally, we copy the build into the shared volume, so gitlab can upload it
    - cp -r "C:/build" "C:/builds/$CI_PROJECT_PATH/scroom_build"
  retry:
    max: 2
    when: runner_system_failure
  artifacts:
    name: "Scroom Portable"
    paths:
      - scroom_build

windows-dev:
  stage: install
  image: 192.168.2.19:4567/roan/scroom-ci:latest
  tags:
    - Windows
  script:
    - cd scroom
    - C:/msys64/usr/bin/bash -c "make install"
    # Finally, we copy the build into the shared volume, so gitlab can upload it
    - cp -r "C:/build" "C:/builds/$CI_PROJECT_PATH/scroom_build"
  retry:
    max: 2
    when: runner_system_failure
  artifacts:
    name: "Scroom Portable"
    paths:
      - scroom_build
