variables:
  GIT_STRATEGY: none

stages:
  - build

build:
  stage: build
  image: 192.168.2.19:4567/roan/scroom-ci:nightly
  tags:
    - Windows
  script:
    - dir
    - if (Test-Path '.\scroom_build') { Remove-Item '.\scroom_build' -Recurse -Force; }
    - dir
    - cd C:\
    - C:/msys64/usr/bin/bash -c "git clone https://gitlab.com/sep-group-2/scroom"
    - dir
    - cd scroom
    - C:/msys64/usr/bin/bash -c "git checkout origin/ci"
    - C:/msys64/usr/bin/bash -c "autoreconf -i"
    - C:/msys64/usr/bin/bash -c "./configure --prefix='C:/build'"
    - C:/msys64/usr/bin/bash -c "make"
    - C:/msys64/usr/bin/bash -c "make install"
    - cp -r "C:/build" "C:/builds/$CI_PROJECT_PATH/scroom_build"
  artifacts:
    paths:
      - scroom_build/
