image: 192.168.2.19:4567/roan/scroom-ci:msys2

build:
  tags:
    - Windows
  script:
    - dir
    - autoreconf  -i
    - bash -l -c "C:\\builds\\roan\\scroom\\configure"
    - make
    - make install