image: 192.168.2.19:4567/roan/scroom-ci:latest

build:
  tags:
    - Windows
  script:
    - dir
    - C:/msys64/usr/bin/bash -c "autoreconf -i"
    - C:/msys64/usr/bin/bash -c "./configure"
    - C:/msys64/usr/bin/bash -c "cat Makefile | sed 's/none\ required//g' > Makefile"
    - C:/msys64/usr/bin/bash -c "make"