stages:
  - build

build-windows:
  # Due to windows docker issues, we can't configure/build in the volume mount.
  # As a workaround, we clone the repo to C:\scroom manually
  variables:
    GIT_STRATEGY: none
    SHELL: "C:/msys64/mingw64.exe -c"
  stage: build
  # This is a windows server core docker image with an msys2 install.
  # It includes all required msys packages
  image: 192.168.2.19:4567/roan/scroom-ci:latest
  tags:
    - Windows
  script:
    - dir
    # This Directory may still persist in gitlab runner cache. If so, we need to remove it.
    - if (Test-Path '.\scroom_build') { Remove-Item '.\scroom_build' -Recurse -Force; }
    - dir
    - cd C:\
    - \& $env:SHELL "git clone https://gitlab.com/sep-group-2/scroom"
    - dir
    - cd scroom
    - \& $env:SHELL "git checkout $CI_COMMIT_SHA"
    - \& $env:SHELL "autoreconf -i"
    - \& $env:SHELL "./configure --prefix='C:/build'"
    - \& $env:SHELL "make 2> /dev/null"
    - \& $env:SHELL "make install-win-portable"
    # Finally, we copy the build into the shared volume, so gitlab can upload it
    - cp -r "C:/build" "C:/builds/$CI_PROJECT_PATH/scroom_build"
  retry:
    max: 2
    when: runner_system_failure
  artifacts:
    paths:
      - scroom_build/
