image: 192.168.2.19:4567/roan/scroom-ci:test3

build:
  tags:
    - Windows
  script:
    - dir
    - C:/msys64/usr/bin/bash -c "autoreconf -i"
    - C:/msys64/usr/bin/bash -c "./configure"
    - C:/msys64/usr/bin/bash -c "PATH=$PATH:C\:\\msys64\\usr\\bin:C\:\\msys64\\mingw64\\bin && make"