stages:
  - build

build:
  stage: build
  image: 192.168.2.19:4567/roan/scroom-ci:latest
  tags:
    - Windows
  script:
    - dir
    - C:/msys64/usr/bin/bash -c "autoreconf -i"
    - C:/msys64/usr/bin/bash -c "./configure"
 #   - C:/msys64/usr/bin/bash -c "sed -i 's/none\ required//g' Makefile"
    - C:/msys64/usr/bin/bash -c "make"
  artifacts:
    paths:
      - "gui/"
      - "setup/prep_windows.ps1"
      - "run_scroom.bat"

build-linux:
  image: gcc
  stage: build
  script:
    - cp ./build_scripts/init.sh ../init.sh
    - chmod 755 ../init.sh
    - cd .. && ./init.sh
  artifacts:
      paths:
        - scroom-build/
