image: gcc
stages:
    - build
    - test

build:
  stage: build
  script:
    - cp ./build_scripts/init.sh ../init.sh
    - chmod 755 ../init.sh
    - cd .. && ./init.sh
    artifacts:
        paths: scroom/build-scroom/


