stages:
  - build

build:
  stage: build
  image: 192.168.2.19:4567/roan/scroom-ci:nightly
  tags:
    - Windows
  script:
    - C:/msys64/usr/bin/bash -c "echo -e 'begin-language: \"Autoconf-without-aclocal-m4\"\\n args: --no-cache \\n end-language: \"Autoconf-without-aclocal-m4\"'"
    - C:/msys64/usr/bin/bash -c "echo -e 'begin-language: \"Autoconf-without-aclocal-m4\"\\n args: --no-cache \\n end-language: \"Autoconf-without-aclocal-m4\"' > .autom4te.cfg"
    - C:/msys64/usr/bin/bash -c "autoreconf -i"
    - C:/msys64/usr/bin/bash -c "./configure --prefix='C:/builds/$CI_PROJECT_PATH/scroom_build'"
    - C:/msys64/usr/bin/bash -c "make"
    - C:/msys64/usr/bin/bash -c "make install"
  artifacts:
    paths:
      - scroom_build/

#build-linux:
#  image: gcc
#  stage: build
#  script:
#    - cp ./build_scripts/init.sh ../init.sh
#    - chmod 755 ../init.sh
#    - cd .. && ./init.sh
#  artifacts:
#      paths:
#        - scroom-build/
