variables:
  GIT_STRATEGY: none

stages:
  - build

build:
  stage: build
  image: 192.168.2.19:4567/roan/scroom-ci:nightly
  tags:
    - Windows
  script:
    - C:/msys64/usr/bin/bash -c "cd C:/ && git clone https://gitlab.com/sep-group-2/scroom && cd scroom"
    - C:/msys64/usr/bin/bash -c "git checkout $CI_COMMIT_SHA"
    - C:/msys64/usr/bin/bash -c "autoreconf -i"
    - C:/msys64/usr/bin/bash -c "./configure --prefix='C:/scroom_build'"
    - C:/msys64/usr/bin/bash -c "make"
    - C:/msys64/usr/bin/bash -c "make install"
  artifacts:
    paths:
      - scroom_build/

#build-linux:
#  image: gcc
#  stage: build
#  script:
#    - cp ./build_scripts/init.sh ../init.sh
#    - chmod 755 ../init.sh
#    - cd .. && ./init.sh
#  artifacts:
#      paths:
#        - scroom-build/
