variables:
  GIT_STRATEGY: none

stages:
  - build

build-windows:
  stage: build
  image: 192.168.2.19:4567/roan/scroom-ci:nightly
  tags:
    - Windows
  script:
    - cd C:/
    - C:/msys64/usr/bin/bash -c "git clone https://gitlab.com/sep-group-2/scroom"
    - cd scroom
    - C:/msys64/usr/bin/bash -c "git checkout origin/ci"
    - C:/msys64/usr/bin/bash -c "autoreconf -i"
    - C:/msys64/usr/bin/bash -c "./configure --prefix='C:/build'"
    - C:/msys64/usr/bin/bash -c "make"
    - C:/msys64/usr/bin/bash -c "make install"
        # We install somewhere else and copy the dir as a workaround to
        # Docker Windows volume mount permission issues
    - cp -r "C:/build" "C:/builds/$CI_PROJECT_PATH/scroom_build"
  artifacts:
    paths:
      - scroom_build/
