stages:
  - build

build:
  stage: build
  image: 192.168.2.19:4567/roan/scroom-ci:latest
  tags:
    - Windows
  script:
    - cd C:\msys64
    - C:/msys64/usr/bin/bash -c "ls -l"
    - cd C:\builds\sep-group-2\scroom
    - dir
    - C:/msys64/usr/bin/bash -c "whoami"
    - C:/msys64/usr/bin/bash -c "chmod -R 755 ./"
    - C:/msys64/usr/bin/bash -c "ls -l"
    - C:/msys64/usr/bin/bash -c "chown -R containeradministrator:containeradministrator ./"
    - C:/msys64/usr/bin/bash -c "ls -l"
    - C:/msys64/usr/bin/bash -c "autoreconf -i || true"
    - C:/msys64/usr/bin/bash -c "ls -l"
    - C:/msys64/usr/bin/bash -c "ls -l autom4te.cache"
    - C:/msys64/usr/bin/bash -c "./configure --prefix='C:/builds/$CI_PROJECT_PATH/scroom_build'"
    - C:/msys64/usr/bin/bash -c "make"
    - C:/msys64/usr/bin/bash -c "make install"
  artifacts:
    paths:
      - scroom_build/

#build-linux:
#  image: gcc
#  stage: build
#  script:
#    - cp ./build_scripts/init.sh ../init.sh
#    - chmod 755 ../init.sh
#    - cd .. && ./init.sh
#  artifacts:
#      paths:
#        - scroom-build/
