language: cpp
script:
- cat /etc/lsb-release &&
  echo TRAVIS_BUILD_NUMBER=${TRAVIS_BUILD_NUMBER} &&
  echo TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER} &&
  echo TRAVIS_BRANCH=${TRAVIS_BRANCH} &&
  echo TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST} &&
  echo SHELL=$SHELL
- ./build_scripts/travis/build-scroom
- true
os:
- linux
dist: bionic
compiler:
- clang
- gcc
env:
- NONE=""
- SOME_DISTS="eoan" OTHER_DISTS="bionic focal"
- DISTCHECK_CONFIGURE_FLAGS='--enable-debug-tiles --disable-multithreading CFLAGS="-g -O0" CXXFLAGS="-g -O0"' LDFLAGS="-Wl,-z,defs"
addons:
  apt:
    packages:
    - libboost-test-dev
    - libboost-dev
    - libboost-filesystem-dev
    - libboost-program-options-dev
    - libboost-system-dev
    - libboost-thread-dev
    - libgtest-dev
    - google-mock
    - libcairo2-dev
    - libglade2-dev
    - libglib2.0-dev
    - libgtk2.0-dev
    - libtiff5-dev
    - pkg-config
    - doxygen
    - graphviz
before_install:
- build_scripts/travis/setup-ssh-keys
git:
  depth: 200
  