language: cpp
script:
- echo TRAVIS_BUILD_NUMBER=${TRAVIS_BUILD_NUMBER} &&
  echo TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER} &&
  echo TRAVIS_BRANCH=${TRAVIS_BRANCH} &&
  echo TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST} &&
  echo SHELL=$SHELL
- $prefix ./build_scripts/travis/build-scroom
os:
- linux
- windows
dist: bionic
compiler:
- gcc
- clang
env:
- NONE=""
- DISTS="true"
- DISTCHECK_CONFIGURE_FLAGS='--enable-debug-tiles --disable-multithreading CFLAGS="-g -O0" CXXFLAGS="-g -O0"' LDFLAGS="-Wl,-z,defs"
jobs:
  exclude:
  - os: linux
    compiler: clang
    env: DISTS="true"
  - os: linux
    compiler: clang
    env: DISTCHECK_CONFIGURE_FLAGS='--enable-debug-tiles --disable-multithreading CFLAGS="-g -O0" CXXFLAGS="-g -O0"' LDFLAGS="-Wl,-z,defs"
  - os: windows
    compiler: clang
  - os: windows
    env: DISTS="true"
  - os: windows
    env: DISTCHECK_CONFIGURE_FLAGS='--enable-debug-tiles --disable-multithreading CFLAGS="-g -O0" CXXFLAGS="-g -O0"' LDFLAGS="-Wl,-z,defs"
addons:
  apt:
    packages:
    - libboost-test-dev
    - libboost-dev
    - libboost-filesystem-dev
    - libboost-program-options-dev
    - libboost-system-dev
    - libboost-thread-dev
    - libgtest-dev
    - google-mock
    - libcairo2-dev
    - libglade2-dev
    - libglib2.0-dev
    - libgtk2.0-dev
    - libtiff5-dev
    - pkg-config
    - doxygen
    - graphviz
git:
  depth: 200
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        $msys2 pacman --sync --noconfirm --needed \
               autoconf \
               automake \
               ccache \
               doxygen \
               git \
               libtool \
               make \
               mingw-w64-x86_64-boost \
               mingw-w64-x86_64-dlfcn \
               mingw-w64-x86_64-gcc \
               mingw-w64-x86_64-glade \
               mingw-w64-x86_64-gtest \
               mingw-w64-x86_64-gtk2 \
               mingw-w64-x86_64-libglade \
               pkg-config \
               zip
        taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export prefix="$mingw64"
        ;;
      *)
        export prefix=""
    esac
- $prefix build_scripts/travis/setup-ssh-keys
