Scroom: ColormapHelper Class Reference
ColormapHelper Class Reference
#include <colormappable.hh>
Static Public Member Functions
static Ptr create (int numberOfColors)
static Ptr createInverted (int numberOfColors)
static Ptr create (Colormap::Ptr const &colormap)
Private Member Functions
ColormapHelper (Colormap::Ptr const &colormap)
Additional Inherited Members
Public Types inherited from ColormapHelperBase
typedef boost::shared_ptr
< ColormapHelperBase > Ptr
Public Types inherited from ColormapProvider
typedef boost::shared_ptr
< ColormapProvider > Ptr
Public Types inherited from Colormappable
typedef boost::shared_ptr
< Colormappable > Ptr
typedef boost::weak_ptr
< Colormappable > WeakPtr
Public Member Functions inherited from ColormapHelperBase
ColormapHelperBase (Colormap::Ptr const &colormap)
virtual void setColormap (Colormap::Ptr colormap)
Request that the presentation use the given colormap.
virtual Colormap::Ptr getOriginalColormap ()
Retrieve the images colormap (if any)
virtual int getNumberOfColors ()
Retrieve the number of colors in use by the presentation.
virtual Color getMonochromeColor ()
virtual void setMonochromeColor (const Color &c)
virtual void setTransparentBackground ()
virtual void disableTransparentBackground ()
virtual bool getTransparentBackground ()
virtual Colormap::Ptr getColormap ()
virtual void setOriginalColormap (Colormap::Ptr colormap)
Public Member Functions inherited from ColormapProvider
virtual ~ColormapProvider ()
Public Member Functions inherited from Colormappable
virtual ~Colormappable ()
Virtual destructor.
Public Attributes inherited from ColormapHelperBase
Colormap::Ptr colormap
Colormap::Ptr originalColormap
Detailed Description
Definition at line 293 of file colormappable.hh.
Constructor & Destructor Documentation
ColormapHelper::ColormapHelper (Colormap::Ptr const & colormap) private
Definition at line 93 of file colormap-helpers.cc.
Referenced by create().
   : ColormapHelperBase(colormap)
 {
 }
Member Function Documentation
ColormapHelper::Ptr ColormapHelper::create (int numberOfColors) static
Definition at line 83 of file colormap-helpers.cc.
Referenced by createInverted(), TiffPresentation::load(), and TiffPresentation::TiffPresentation().
 {
   return create(Colormap::createDefault(numberOfColors));
 }
ColormapHelper::Ptr ColormapHelper::create (Colormap::Ptr const & colormap) static
Definition at line 78 of file colormap-helpers.cc.
 {
   return Ptr(new ColormapHelper(colormap));
 }
ColormapHelper::Ptr ColormapHelper::createInverted (int numberOfColors) static
Definition at line 88 of file colormap-helpers.cc.
 {
   return create(Colormap::createDefaultInverted(numberOfColors));
 }
The documentation for this class was generated from the following files:
inc/scroom/colormappable.hh
libs/scroom/src/colormap-helpers.cc