Scroom: inc/scroom/colormappable.hh File Reference
colormappable.hh File Reference
#include <stdint.h>
#include <vector>
#include <string>
#include <cmath>
#include <boost/shared_ptr.hpp>
#include <boost/weak_ptr.hpp>
#include <boost/operators.hpp>
#include <scroom/presentationinterface.hh>
#include <scroom/observable.hh>
Classes
class Color
Represent a (ARGB) color.
class Colormap
Represent a colormap.
class Colormappable
Interface for Colormappable presentations.
class ColormapProvider
class ColormapHelperBase
class ColormapHelper
class MonochromeColormapHelper
Namespaces
anonymous_namespace{colormappable.hh}
Macros
#define GCC_VERSION
#define NORETURN __attribute__((noreturn))
Functions
uint8_t byteFromDouble (double d)
double doubleFromByte (uint8_t b)
uint16_t shortFromDouble (double d)
double anonymous_namespace{colormappable.hh}::computeC (double c)
Color mix (const Color &a, const Color &b, double alpha)
Variables
const std::string COLORMAPPABLE_PROPERTY_NAME ="Colormappable"
const std::string MONOCHROME_COLORMAPPABLE_PROPERTY_NAME ="Monochrome Colormappable"
const std::string TRANSPARENT_BACKGROUND_PROPERTY_NAME ="Transparent Background"
Macro Definition Documentation
#define GCC_VERSION
Value:
(__GNUC__ * 10000           \
                     + __GNUC_MINOR__ * 100     \
                     + __GNUC_PATCHLEVEL__)
Definition at line 41 of file colormappable.hh.
#define NORETURN __attribute__((noreturn))
Definition at line 46 of file colormappable.hh.
Function Documentation
uint8_t byteFromDouble (double d) inline
Definition at line 28 of file colormappable.hh.
Referenced by Color::getARGB32(), and Color::getRGB24().
 { return uint8_t(255*d); }
double doubleFromByte (uint8_t b) inline
Definition at line 29 of file colormappable.hh.
 { return b/255.0; }
Color mix (const Color & a, const Color & b, double alpha) inline
Definition at line 116 of file colormappable.hh.
Referenced by Operations8bpp::cache(), OperationsColormapped::cache(), Operations8bpp::draw(), and MonochromeColormapHelper::regenerateColormap().
 {
   return a*alpha + b*(1.0-alpha);
 }
uint16_t shortFromDouble (double d) inline
Definition at line 30 of file colormappable.hh.
Referenced by Color::getGdkColor().
 { return uint16_t(0xFFFF*d); }
Variable Documentation
const std::string COLORMAPPABLE_PROPERTY_NAME ="Colormappable"
Definition at line 24 of file colormappable.hh.
Referenced by TiffPresentation::load().
const std::string MONOCHROME_COLORMAPPABLE_PROPERTY_NAME ="Monochrome Colormappable"
Definition at line 25 of file colormappable.hh.
Referenced by TransparentOverlayPresentation::addPresentation(), TiffPresentation::load(), TransparentOverlayPresentation::setOptimalColor(), and anonymous_namespace{transparentoverlayviewinfo.cc}::setToggleButtonColor().
const std::string TRANSPARENT_BACKGROUND_PROPERTY_NAME ="Transparent Background"
Definition at line 26 of file colormappable.hh.
Referenced by TransparentOverlayViewInfo::redraw().