Scroom: RoiUi Class Reference
RoiUi Class Reference
#include <roiui.hh>
Public Types
typedef boost::shared_ptr< RoiUi > Ptr
Public Types inherited from Viewable
typedef boost::shared_ptr
< Viewable > Ptr
typedef boost::weak_ptr< Viewable > WeakPtr
Public Member Functions
~RoiUi ()
virtual void open (ViewInterface::WeakPtr vi)
Gets called just after the View is created.
virtual void close (ViewInterface::WeakPtr vi)
Gets called just before the View is destroyed.
Public Member Functions inherited from Scroom::Utils::Base
virtual ~Base ()
template<typename R >
boost::shared_ptr< R > shared_from_this ()
Calls shared_from_this() with a built-in dynamic cast, to make it usable in subclasses.
template<typename R >
boost::shared_ptr< R const > shared_from_this () const
Calls shared_from_this() with a built-in dynamic cast, to make it usable in subclasses.
Public Member Functions inherited from Viewable
virtual ~Viewable ()
Static Public Member Functions
static Ptr create (const std::string &fileName, ScroomInterface::Ptr const &scroomInterface)
Private Member Functions
RoiUi ()
void init (std::string const &fileName, ScroomInterface::Ptr const &scroomInterface)
void create_and_fill_model ()
GtkWidget * create_view_and_model ()
Static Private Member Functions
static void addRoiItemsToModel (GtkTreeStore *store, GtkTreeIter *base, std::vector< Scroom::Roi::RoiItem > const &regions)
Private Attributes
Scroom::Roi::List::Ptr list
GtkTreeModel * model
Scroom::Utils::StuffList stuff
Detailed Description
Definition at line 15 of file roiui.hh.
Member Typedef Documentation
typedef boost::shared_ptr<RoiUi> RoiUi::Ptr
Definition at line 18 of file roiui.hh.
Constructor & Destructor Documentation
RoiUi::RoiUi () private
Definition at line 56 of file roiui.cc.
Referenced by create().
              :
     model(NULL)
 {}
RoiUi::~RoiUi ()
Definition at line 60 of file roiui.cc.
 {
   if(model)
   {
     g_object_unref (model);
     model = NULL;
   }
 }
Member Function Documentation
void RoiUi::addRoiItemsToModel (GtkTreeStore * store, GtkTreeIter * base, std::vector< Scroom::Roi::RoiItem > const & regions) static private
Definition at line 85 of file roiui.cc.
Referenced by create_and_fill_model().
 {
   GtkTreeIter iter;
   for(auto const& item: regions)
   {
     Scroom::Roi::RoiBase const& r = getBase(item);
     gtk_tree_store_append (store, &iter, base);
     gtk_tree_store_set (store, &iter,
                         COL_NAME, r.str().c_str(),
                         COL_POINTER, &r,
                         -1);
     addRoiItemsToModel(store, &iter, r.children);
   }
 }
void RoiUi::close (ViewInterface::WeakPtr vi) virtual
Gets called just before the View is destroyed.
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implements Viewable.
Definition at line 149 of file roiui.cc.
 {}
RoiUi::Ptr RoiUi::create (const std::string & fileName, ScroomInterface::Ptr const & scroomInterface) static
Definition at line 48 of file roiui.cc.
Referenced by RoiPlugin::open().
 {
   Ptr result = Ptr(new RoiUi());
   result->init(fileName, scroomInterface);
   return result;
 }
void RoiUi::create_and_fill_model () private
Definition at line 103 of file roiui.cc.
Referenced by create_view_and_model().
 {
   GtkTreeStore  *store;
   store = gtk_tree_store_new (NUM_COLS, G_TYPE_STRING, G_TYPE_POINTER);
   addRoiItemsToModel(store, NULL, list->regions);
   model = GTK_TREE_MODEL(store);
 }
GtkWidget * RoiUi::create_view_and_model () private
Definition at line 114 of file roiui.cc.
Referenced by open().
 {
   GtkCellRenderer     *renderer;
   GtkWidget           *view;
   view = gtk_tree_view_new ();
   /* --- Column #1 --- */
   renderer = gtk_cell_renderer_text_new ();
   gtk_tree_view_insert_column_with_attributes (GTK_TREE_VIEW (view),
                                                -1,
                                                "Name",
                                                renderer,
                                                "text", COL_NAME,
                                                NULL);
   create_and_fill_model();
   gtk_tree_view_set_model (GTK_TREE_VIEW (view), model);
   return view;
 }
void RoiUi::init (std::string const & fileName, ScroomInterface::Ptr const & scroomInterface) private
Definition at line 69 of file roiui.cc.
 {
   list = Scroom::Roi::parse(fileName);
   printf("Regions: %zu\n", list->regions.size());
   std::set<ViewObservable::Ptr> viewObservables = list->instantiate(scroomInterface, fileName);
   if(!viewObservables.empty() && !list->regions.empty())
   {
     for(auto const & viewObservable: viewObservables)
     {
       stuff.push_back(viewObservable->registerStrongObserver(shared_from_this<RoiUi>()));
     }
   }
 }
void RoiUi::open (ViewInterface::WeakPtr vi) virtual
Gets called just after the View is created.
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implements Viewable.
Definition at line 138 of file roiui.cc.
 {
   ViewInterface::Ptr vi = viWeak.lock();
   if(vi)
   {
     GtkWidget* view = create_view_and_model();
     vi->addSideWidget("Roi", view);
   }
 }
Member Data Documentation
Scroom::Roi::List::Ptr RoiUi::list private
Definition at line 21 of file roiui.hh.
Referenced by create_and_fill_model(), and init().
GtkTreeModel* RoiUi::model private
Definition at line 22 of file roiui.hh.
Referenced by create_and_fill_model(), create_view_and_model(), and ~RoiUi().
Scroom::Utils::StuffList RoiUi::stuff private
Definition at line 24 of file roiui.hh.
Referenced by init().
The documentation for this class was generated from the following files:
plugins/roi/src/roiui.hh
plugins/roi/src/roiui.cc