Scroom: ProgressBarManager Class Reference
ProgressBarManager Class Reference
#include <progressbarmanager.hh>
Public Types
typedef boost::shared_ptr
< ProgressBarManager > Ptr
Public Types inherited from ProgressInterface
typedef boost::shared_ptr
< ProgressInterface > Ptr
typedef boost::weak_ptr
< ProgressInterface > WeakPtr
Public Member Functions
~ProgressBarManager ()
void setProgressBar (GtkProgressBar *progressBar)
virtual void setIdle ()
virtual void setWaiting (double progress=0.0)
virtual void setWorking (double progress)
virtual void setFinished ()
Public Member Functions inherited from ProgressInterface
virtual ~ProgressInterface ()
Static Public Member Functions
static Ptr create (GtkProgressBar *progressBar=NULL)
Private Member Functions
ProgressBarManager (GtkProgressBar *progressBar)
void stopWaiting ()
void startWaiting ()
Private Attributes
GtkProgressBar * progressBar
bool isWaiting
Detailed Description
Definition at line 14 of file progressbarmanager.hh.
Member Typedef Documentation
typedef boost::shared_ptr<ProgressBarManager> ProgressBarManager::Ptr
Definition at line 17 of file progressbarmanager.hh.
Constructor & Destructor Documentation
ProgressBarManager::ProgressBarManager (GtkProgressBar * progressBar) private
Definition at line 105 of file progressbarmanager.cc.
Referenced by create().
   :progressBar(progressBar), isWaiting(false)
 {}
ProgressBarManager::~ProgressBarManager ()
Definition at line 114 of file progressbarmanager.cc.
 {
   stopWaiting();
 }
Member Function Documentation
ProgressBarManager::Ptr ProgressBarManager::create (GtkProgressBar * progressBar = NULL) static
Definition at line 109 of file progressbarmanager.cc.
Referenced by View::View().
 {
   return Ptr(new ProgressBarManager(progressBar));
 }
void ProgressBarManager::setFinished () virtual
Implements ProgressInterface.
Definition at line 165 of file progressbarmanager.cc.
 {
   setIdle();
 }
void ProgressBarManager::setIdle () virtual
Implements ProgressInterface.
Definition at line 147 of file progressbarmanager.cc.
Referenced by setFinished().
 {
   setWorking(0.0);
 }
void ProgressBarManager::setProgressBar (GtkProgressBar * progressBar)
Definition at line 119 of file progressbarmanager.cc.
 {
   stopWaiting();
   this->progressBar = progressBar;
 }
void ProgressBarManager::setWaiting (double progress = 0.0) virtual
Implements ProgressInterface.
Definition at line 152 of file progressbarmanager.cc.
 {
   startWaiting();
 }
void ProgressBarManager::setWorking (double progress) virtual
Implements ProgressInterface.
Definition at line 157 of file progressbarmanager.cc.
Referenced by setIdle().
 {
   stopWaiting();
   Scroom::GtkHelpers::TakeGdkLock gdkLock;
   gtk_progress_bar_set_fraction(progressBar, progress);
 }
void ProgressBarManager::startWaiting () private
Definition at line 125 of file progressbarmanager.cc.
Referenced by setWaiting().
 {
   if(!isWaiting)
   {
     // Start pulsing
     instance()->start(progressBar);
     isWaiting = true;
   }
 }
void ProgressBarManager::stopWaiting () private
Definition at line 135 of file progressbarmanager.cc.
Referenced by setProgressBar(), setWorking(), and ~ProgressBarManager().
 {
   if(isWaiting)
   {
     // Stop pulsing
     instance()->stop(progressBar);
     isWaiting = false;
   }
 }
Member Data Documentation
bool ProgressBarManager::isWaiting private
Definition at line 21 of file progressbarmanager.hh.
Referenced by startWaiting(), and stopWaiting().
GtkProgressBar* ProgressBarManager::progressBar private
Definition at line 20 of file progressbarmanager.hh.
Referenced by setProgressBar(), setWorking(), startWaiting(), and stopWaiting().
The documentation for this class was generated from the following files:
gui/src/progressbarmanager.hh
gui/src/progressbarmanager.cc