Scroom: Scroom::GtkHelpers::Detail Namespace Reference
Scroom::GtkHelpers::Detail Namespace Reference
Classes
class Wrapper
Functions
static int gtkWrapper (gpointer data)
boost::recursive_mutex & GdkMutex ()
void lockGdkMutex ()
void unlockGdkMutex ()
Function Documentation
boost::recursive_mutex& Scroom::GtkHelpers::Detail::GdkMutex ()
Definition at line 63 of file gtk-helpers.cc.
Referenced by lockGdkMutex(), and unlockGdkMutex().
       {
         static boost::recursive_mutex me;
         return me;
       }
static int Scroom::GtkHelpers::Detail::gtkWrapper (gpointer data) static
Definition at line 41 of file gtk-helpers.cc.
       {
         Wrapper* w = reinterpret_cast<Wrapper*>(data);
         bool result = w->f();
         if(!result)
           delete w;
         return result;
       }
void Scroom::GtkHelpers::Detail::lockGdkMutex ()
Definition at line 69 of file gtk-helpers.cc.
Referenced by Scroom::GtkHelpers::useRecursiveGdkLock().
       {
         GdkMutex().lock();
       }
void Scroom::GtkHelpers::Detail::unlockGdkMutex ()
Definition at line 74 of file gtk-helpers.cc.
Referenced by Scroom::GtkHelpers::useRecursiveGdkLock().
       {
         GdkMutex().unlock();
       }