Scroom: ThreadPool::Queue Class Reference
ThreadPool::Queue Class Reference
Represent a Queue in the ThreadPool.
#include <threadpool.hh>
Public Types
typedef boost::shared_ptr< Queue > Ptr
typedef boost::weak_ptr< Queue > WeakPtr
Public Member Functions
~Queue ()
boost::shared_ptr
< Scroom::Detail::ThreadPool::QueueImpl > get ()
boost::shared_ptr< WeakQueue > getWeak ()
Static Public Member Functions
static Ptr create ()
When the last reference goes out of scope, synchronously destroy the Queue, blocking until any currently running jobs are finished.
static Ptr createAsync ()
When the last reference goes out of scope, asynchronously destroy the Queue.
Private Member Functions
Queue ()
Private Attributes
boost::shared_ptr< WeakQueue > weak
Detailed Description
Represent a Queue in the ThreadPool.
If pass in a Queue object when you schedule() your job, then your job will be scheduled on that particular queue. This does not in any way affect the order in which jobs are executed. Use priority for that. Instead, if you later delete your Queue, any jobs scheduled on that Queue will not be executed any more.
When you delete the Queue, your thread will block until any jobs currently being executed have finished. I.e. after the Queue is destroyed, no jobs will be running any more, nor will any be run in the future. This can cause deadlocks if a job running on a ThreadPool tries to destroy its own queue.
To avoid deadlock, you should make sure that jobs running on the ThreadPool only have references to WeakQueue objects, or you should create your Queue using createAsync(). This will do the actual Queue destruction on a separate thread. As a result, after the last reference to the Queue object goes out of scope, jobs on the Queue may continue running for some time.
Note
If you delete the Queue, the associated jobs will not actually be deleted. Instead, when the time comes to execute the job, a check is done whether the Queue still exists. If it doesn't, the job is silently discarded.
Definition at line 85 of file threadpool.hh.
Member Typedef Documentation
typedef boost::shared_ptr<Queue> ThreadPool::Queue::Ptr
Definition at line 88 of file threadpool.hh.
typedef boost::weak_ptr<Queue> ThreadPool::Queue::WeakPtr
Definition at line 89 of file threadpool.hh.
Constructor & Destructor Documentation
ThreadPool::Queue::~Queue ()
Definition at line 375 of file threadpoolimpl.cc.
 {
   weak->get()->deletingQueue();
 }
ThreadPool::Queue::Queue () private
Definition at line 370 of file threadpoolimpl.cc.
 : weak(WeakQueue::create())
 {
 }
Member Function Documentation
ThreadPool::Queue::Ptr ThreadPool::Queue::create () static
When the last reference goes out of scope, synchronously destroy the Queue, blocking until any currently running jobs are finished.
ThreadPool::Queue.
Definition at line 360 of file threadpoolimpl.cc.
Referenced by ThreadPool::defaultQueue(), and CompressedTile::observerAdded().
 {
   return ThreadPool::Queue::Ptr(new ThreadPool::Queue());
 }
ThreadPool::Queue::Ptr ThreadPool::Queue::createAsync () static
When the last reference goes out of scope, asynchronously destroy the Queue.
Jobs scheduled on the Queue may continue running for some time.
Definition at line 365 of file threadpoolimpl.cc.
Referenced by TileViewState::kick().
 {
   return ThreadPool::Queue::Ptr(new ThreadPool::Queue(), AsyncDeleter<ThreadPool::Queue>());
 }
QueueImpl::Ptr ThreadPool::Queue::get ()
Definition at line 380 of file threadpoolimpl.cc.
 {
   return weak->get();
 }
ThreadPool::WeakQueue::Ptr ThreadPool::Queue::getWeak ()
Definition at line 385 of file threadpoolimpl.cc.
 {
   return weak;
 }
Member Data Documentation
boost::shared_ptr<WeakQueue> ThreadPool::Queue::weak private
Definition at line 113 of file threadpool.hh.
The documentation for this class was generated from the following files:
inc/scroom/threadpool.hh
libs/threadpool/src/threadpoolimpl.cc