Scroom: PluginInformationInterface Class Reference
PluginInformationInterface Class Reference abstract
#include <plugininformationinterface.hh>
Public Types
typedef boost::shared_ptr< PluginInformationInterface > Ptr
Public Member Functions
PluginInformationInterface ()
virtual ~PluginInformationInterface ()
virtual std::string getPluginName ()=0
virtual std::string getPluginVersion ()=0
virtual void registerCapabilities (ScroomPluginInterface::Ptr host)=0
Public Attributes
const int pluginApiVersion
Detailed Description
Definition at line 16 of file plugininformationinterface.hh.
Member Typedef Documentation
Ptr
typedef boost::shared_ptr<PluginInformationInterface> PluginInformationInterface::Ptr
Definition at line 19 of file plugininformationinterface.hh.
Constructor & Destructor Documentation
PluginInformationInterface()
PluginInformationInterface::PluginInformationInterface () inline
Definition at line 25 of file plugininformationinterface.hh.
     : pluginApiVersion(PLUGIN_API_VERSION)
   {}
~PluginInformationInterface()
virtual PluginInformationInterface::~PluginInformationInterface () inline virtual
Definition at line 29 of file plugininformationinterface.hh.
 {}
Member Function Documentation
getPluginName()
virtual std::string PluginInformationInterface::getPluginName () pure virtual
Implemented in Tiff, and TransparentOverlay.
Referenced by ~PluginInformationInterface().
getPluginVersion()
virtual std::string PluginInformationInterface::getPluginVersion () pure virtual
Implemented in Tiff, and TransparentOverlay.
Referenced by ~PluginInformationInterface().
registerCapabilities()
virtual void PluginInformationInterface::registerCapabilities (ScroomPluginInterface::Ptr host) pure virtual
Implemented in Tiff, and TransparentOverlay.
Referenced by ~PluginInformationInterface().
Member Data Documentation
pluginApiVersion
const int PluginInformationInterface::pluginApiVersion
Definition at line 22 of file plugininformationinterface.hh.
The documentation for this class was generated from the following file:
inc/scroom/plugininformationinterface.hh