Scroom: Scroom::Utils::Segment< T > Class Template Reference
Scroom::Utils::Segment< T > Class Template Reference
#include <linearsegment.hh>
Public Types
typedef T value_type
Public Member Functions
Segment ()
Segment (value_type start_, value_type size_)
Segment (Segment< int > const &other)
Segment moveTo (value_type p) const
bool contains (value_type p) const
bool contains (const Segment< value_type > &other) const
bool intersects (const Segment< value_type > &other) const
void reduceSizeToMultipleOf (value_type m)
Segment< value_type > intersection (const Segment< value_type > &other) const
void intersect (const Segment< value_type > &other)
Segment< value_type > before (value_type v) const
Segment< value_type > after (value_type v) const
value_type getStart () const
value_type getEnd () const
value_type getSize () const
bool isEmpty () const
bool operator== (const Segment< value_type > &other) const
bool operator!= (const Segment< value_type > &other) const
Segment< value_type > & operator+= (value_type n)
Segment< value_type > & operator-= (value_type n)
Segment< value_type > & operator*= (value_type n)
Segment< value_type > & operator/= (value_type n)
Segment< value_type > & operator&= (const Segment< value_type > &other)
void setSize (value_type n)
Private Attributes
value_type start
value_type size
Detailed Description
template<typename T>
class Scroom::Utils::Segment< T >
Definition at line 42 of file linearsegment.hh.
Member Typedef Documentation
template<typename T> typedef T Scroom::Utils::Segment< T >::value_type
Definition at line 49 of file linearsegment.hh.
Constructor & Destructor Documentation
template<typename T> Scroom::Utils::Segment< T >::Segment () inline
Definition at line 51 of file linearsegment.hh.
Referenced by Scroom::Utils::Segment< value_type >::moveTo().
         : start (0), size (0)
       {}
template<typename T> Scroom::Utils::Segment< T >::Segment (value_type start_, value_type size_) inline
Definition at line 55 of file linearsegment.hh.
         : start (start_), size (size_)
       {
         if (size < 0)
         {
           start += size;
           size = -size;
         }
       }
template<typename T> Scroom::Utils::Segment< T >::Segment (Segment< int > const & other) inline
Definition at line 65 of file linearsegment.hh.
         : start(other.getStart()), size(other.getSize())
       {}
Member Function Documentation
template<typename T> Segment<value_type> Scroom::Utils::Segment< T >::after (value_type v) const inline
Definition at line 120 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< double >::below(), and Scroom::Utils::Rectangle< double >::rightOf().
       {
         if(v > start+size)
           return Segment<value_type>();
         if(v > start)
           return Segment<value_type>(v, start+size-v);
         return *this;
       }
template<typename T> Segment<value_type> Scroom::Utils::Segment< T >::before (value_type v) const inline
Definition at line 111 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< double >::above(), and Scroom::Utils::Rectangle< double >::leftOf().
       {
         if(v < start)
           return Segment<value_type>();
         if(v < start+size)
           return Segment<value_type>(start, v-start);
         return *this;
       }
template<typename T> bool Scroom::Utils::Segment< T >::contains (value_type p) const inline
Definition at line 74 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< double >::contains().
       {
         return start <= p && p < (start + size);
       }
template<typename T> bool Scroom::Utils::Segment< T >::contains (const Segment< value_type > & other) const inline
Definition at line 79 of file linearsegment.hh.
       {
         return getStart () <= other.getStart () && other.getEnd () <= getEnd ();
       }
template<typename T> value_type Scroom::Utils::Segment< T >::getEnd () const inline
Definition at line 134 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< double >::below(), Scroom::Utils::Segment< value_type >::contains(), Scroom::Utils::Rectangle< double >::getBottom(), Scroom::Utils::Rectangle< double >::getBottomLeft(), Scroom::Utils::Rectangle< double >::getBottomRight(), Scroom::Utils::Rectangle< double >::getRight(), Scroom::Utils::Rectangle< double >::getTopRight(), Scroom::Utils::Segment< value_type >::intersection(), Scroom::Utils::Segment< value_type >::intersects(), and Scroom::Utils::Rectangle< double >::rightOf().
       {
         return start + size;
       }
template<typename T> value_type Scroom::Utils::Segment< T >::getSize () const inline
Definition at line 139 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< double >::getHeight(), Scroom::Utils::Rectangle< double >::getSize(), Scroom::Utils::Rectangle< double >::getWidth(), and Scroom::Utils::Segment< value_type >::isEmpty().
       {
         return size;
       }
template<typename T> value_type Scroom::Utils::Segment< T >::getStart () const inline
Definition at line 129 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< double >::above(), Scroom::Utils::Segment< value_type >::contains(), Scroom::Utils::Rectangle< double >::getBottomLeft(), Scroom::Utils::Rectangle< double >::getLeft(), Scroom::Utils::Rectangle< double >::getTop(), Scroom::Utils::Rectangle< double >::getTopLeft(), Scroom::Utils::Rectangle< double >::getTopRight(), Scroom::Utils::Segment< value_type >::intersection(), Scroom::Utils::Segment< value_type >::intersects(), Scroom::Utils::Rectangle< double >::leftOf(), and Scroom::Utils::operator<<().
       {
         return start;
       }
template<typename T> void Scroom::Utils::Segment< T >::intersect (const Segment< value_type > & other) inline
Definition at line 106 of file linearsegment.hh.
Referenced by Scroom::Utils::Segment< value_type >::operator&=().
       {
         *this = intersection (other);
       }
template<typename T> Segment<value_type> Scroom::Utils::Segment< T >::intersection (const Segment< value_type > & other) const inline
Definition at line 94 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< double >::above(), Scroom::Utils::Rectangle< double >::below(), Scroom::Utils::Segment< value_type >::intersect(), Scroom::Utils::Rectangle< double >::intersection(), Scroom::Utils::Rectangle< double >::leftOf(), and Scroom::Utils::Rectangle< double >::rightOf().
       {
         const value_type newStart = std::max (getStart (), other.getStart ());
         const value_type newEnd = std::min (getEnd (), other.getEnd ());
         const value_type newSize = newEnd - newStart;
         if (newSize >= 0)
           return Segment<value_type> (newStart, newSize);
         else
           return Segment<value_type> (); // empty segment
       }
template<typename T> bool Scroom::Utils::Segment< T >::intersects (const Segment< value_type > & other) const inline
Definition at line 84 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< double >::intersects().
       {
         return getStart () < other.getEnd () && other.getStart () < getEnd () && !isEmpty () && !other.isEmpty ();
       }
template<typename T> bool Scroom::Utils::Segment< T >::isEmpty () const inline
Definition at line 144 of file linearsegment.hh.
Referenced by Scroom::Utils::Segment< value_type >::intersects(), Scroom::Utils::Rectangle< double >::isEmpty(), and Scroom::Utils::Segment< value_type >::operator==().
       {
         return isZero(getSize());
       }
template<typename T> Segment Scroom::Utils::Segment< T >::moveTo (value_type p) const inline
Definition at line 69 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< double >::moveTo().
       {
         return Segment(p, size);
       }
template<typename T> bool Scroom::Utils::Segment< T >::operator!= (const Segment< value_type > & other) const inline
Definition at line 159 of file linearsegment.hh.
       {
         return !(*this == other);
       }
template<typename T> Segment<value_type>& Scroom::Utils::Segment< T >::operator&= (const Segment< value_type > & other) inline
Definition at line 186 of file linearsegment.hh.
       {
         intersect (other);
         return *this;
       }
template<typename T> Segment<value_type>& Scroom::Utils::Segment< T >::operator*= (value_type n) inline
Definition at line 174 of file linearsegment.hh.
       {
         start *= n;
         size *= n;
         return *this;
       }
template<typename T> Segment<value_type>& Scroom::Utils::Segment< T >::operator+= (value_type n) inline
Definition at line 164 of file linearsegment.hh.
       {
         start += n;
         return *this;
       }
template<typename T> Segment<value_type>& Scroom::Utils::Segment< T >::operator-= (value_type n) inline
Definition at line 169 of file linearsegment.hh.
       {
         start -= n;
         return *this;
       }
template<typename T> Segment<value_type>& Scroom::Utils::Segment< T >::operator/= (value_type n) inline
Definition at line 180 of file linearsegment.hh.
       {
         start /= n;
         size /= n;
         return *this;
       }
template<typename T> bool Scroom::Utils::Segment< T >::operator== (const Segment< value_type > & other) const inline
Definition at line 149 of file linearsegment.hh.
       {
         if(isEmpty() != other.isEmpty())
           return false;
         else if(isEmpty())
           return true;
         else
           return areEqual(start, other.start) && areEqual(size, other.size);
       }
template<typename T> void Scroom::Utils::Segment< T >::reduceSizeToMultipleOf (value_type m) inline
Definition at line 89 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< double >::reduceSizeToMultipleOf().
       {
         size -= size % m;
       }
template<typename T> void Scroom::Utils::Segment< T >::setSize (value_type n) inline
Definition at line 191 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< double >::setSize().
       {
         size = n;
       }
Member Data Documentation
template<typename T> value_type Scroom::Utils::Segment< T >::size private
Definition at line 198 of file linearsegment.hh.
Referenced by Scroom::Utils::Segment< value_type >::after(), Scroom::Utils::Segment< value_type >::before(), Scroom::Utils::Segment< value_type >::contains(), Scroom::Utils::Segment< value_type >::getEnd(), Scroom::Utils::Segment< value_type >::getSize(), Scroom::Utils::Segment< value_type >::moveTo(), Scroom::Utils::Segment< value_type >::operator*=(), Scroom::Utils::Segment< value_type >::operator/=(), Scroom::Utils::Segment< value_type >::operator==(), Scroom::Utils::Segment< value_type >::reduceSizeToMultipleOf(), Scroom::Utils::Segment< value_type >::Segment(), and Scroom::Utils::Segment< value_type >::setSize().
template<typename T> value_type Scroom::Utils::Segment< T >::start private
Definition at line 197 of file linearsegment.hh.
Referenced by Scroom::Utils::Segment< value_type >::after(), Scroom::Utils::Segment< value_type >::before(), Scroom::Utils::Segment< value_type >::contains(), Scroom::Utils::Segment< value_type >::getEnd(), Scroom::Utils::Segment< value_type >::getStart(), Scroom::Utils::Segment< value_type >::operator*=(), Scroom::Utils::Segment< value_type >::operator+=(), Scroom::Utils::Segment< value_type >::operator-=(), Scroom::Utils::Segment< value_type >::operator/=(), Scroom::Utils::Segment< value_type >::operator==(), and Scroom::Utils::Segment< value_type >::Segment().
The documentation for this class was generated from the following file:
inc/scroom/linearsegment.hh