Scroom: Segment< T > Class Template Reference
Segment< T > Class Template Reference
#include <linearsegment.hh>
Public Types
typedef T value_type
Public Member Functions
Segment ()
Segment (value_type start_, value_type size_)
Segment (Segment< int > const &other)
Segment moveTo (value_type p) const
bool contains (value_type p) const
bool contains (const Segment< value_type > &other) const
bool intersects (const Segment< value_type > &other) const
void reduceSizeToMultipleOf (value_type m)
Segment< value_type > intersection (const Segment< value_type > &other) const
void intersect (const Segment< value_type > &other)
Segment< value_type > before (value_type v) const
Segment< value_type > after (value_type v) const
value_type getStart () const
value_type getEnd () const
value_type getSize () const
bool isEmpty () const
bool operator== (const Segment< value_type > &other) const
bool operator!= (const Segment< value_type > &other) const
Segment< value_type > & operator+= (value_type n)
Segment< value_type > & operator-= (value_type n)
Segment< value_type > & operator*= (value_type n)
Segment< value_type > & operator/= (value_type n)
Segment< value_type > & operator&= (const Segment< value_type > &other)
void setSize (value_type n)
Private Attributes
value_type start
value_type size
Detailed Description
template<typename T>
class Segment< T >
Definition at line 39 of file linearsegment.hh.
Member Typedef Documentation
template<typename T> typedef T Segment< T >::value_type
Definition at line 46 of file linearsegment.hh.
Constructor & Destructor Documentation
template<typename T> Segment< T >::Segment () inline
Definition at line 48 of file linearsegment.hh.
Referenced by Segment< value_type >::moveTo().
       : start (0), size (0)
   {}
template<typename T> Segment< T >::Segment (value_type start_, value_type size_) inline
Definition at line 52 of file linearsegment.hh.
       : start (start_), size (size_)
   {
     if (size < 0)
     {
       start += size;
       size = -size;
     }
   }
template<typename T> Segment< T >::Segment (Segment< int > const & other) inline
Definition at line 62 of file linearsegment.hh.
     : start(other.getStart()), size(other.getSize())
   {}
Member Function Documentation
template<typename T> Segment<value_type> Segment< T >::after (value_type v) const inline
Definition at line 117 of file linearsegment.hh.
Referenced by Rectangle< T >::below(), and Rectangle< T >::rightOf().
   {
     if(v > start+size)
       return Segment<value_type>();
     if(v > start)
       return Segment<value_type>(v, start+size-v);
     return *this;
   }
template<typename T> Segment<value_type> Segment< T >::before (value_type v) const inline
Definition at line 108 of file linearsegment.hh.
Referenced by Rectangle< T >::above(), and Rectangle< T >::leftOf().
   {
     if(v < start)
       return Segment<value_type>();
     if(v < start+size)
       return Segment<value_type>(start, v-start);
     return *this;
   }
template<typename T> bool Segment< T >::contains (value_type p) const inline
Definition at line 71 of file linearsegment.hh.
Referenced by Rectangle< T >::contains().
   {
     return start <= p && p < (start + size);
   }
template<typename T> bool Segment< T >::contains (const Segment< value_type > & other) const inline
Definition at line 76 of file linearsegment.hh.
   {
     return getStart () <= other.getStart () && other.getEnd () <= getEnd ();
   }
template<typename T> value_type Segment< T >::getEnd () const inline
Definition at line 131 of file linearsegment.hh.
Referenced by Rectangle< T >::below(), Segment< value_type >::contains(), Rectangle< T >::getBottomLeft(), Rectangle< T >::getBottomPos(), Rectangle< T >::getBottomRight(), Rectangle< T >::getRightPos(), Rectangle< T >::getTopRight(), Segment< value_type >::intersection(), Segment< value_type >::intersects(), and Rectangle< T >::rightOf().
   {
     return start + size;
   }
template<typename T> value_type Segment< T >::getSize () const inline
Definition at line 136 of file linearsegment.hh.
Referenced by Rectangle< T >::getHeight(), Rectangle< T >::getWidth(), and Segment< value_type >::isEmpty().
   {
     return size;
   }
template<typename T> value_type Segment< T >::getStart () const inline
Definition at line 126 of file linearsegment.hh.
Referenced by Rectangle< T >::above(), Segment< value_type >::contains(), Rectangle< T >::getBottomLeft(), Rectangle< T >::getLeftPos(), Rectangle< T >::getTopLeft(), Rectangle< T >::getTopPos(), Rectangle< T >::getTopRight(), Segment< value_type >::intersection(), Segment< value_type >::intersects(), Rectangle< T >::leftOf(), and operator<<().
   {
     return start;
   }
template<typename T> void Segment< T >::intersect (const Segment< value_type > & other) inline
Definition at line 103 of file linearsegment.hh.
Referenced by Segment< value_type >::operator&=().
   {
     *this = intersection (other);
   }
template<typename T> Segment<value_type> Segment< T >::intersection (const Segment< value_type > & other) const inline
Definition at line 91 of file linearsegment.hh.
Referenced by Rectangle< T >::above(), Rectangle< T >::below(), Segment< value_type >::intersect(), Rectangle< T >::intersection(), Rectangle< T >::leftOf(), and Rectangle< T >::rightOf().
   {
     const value_type newStart = std::max (getStart (), other.getStart ());
     const value_type newEnd = std::min (getEnd (), other.getEnd ());
     const value_type newSize = newEnd - newStart;
     if (newSize >= 0)
       return Segment<value_type> (newStart, newSize);
     else
       return Segment<value_type> (); // empty segment
   }
template<typename T> bool Segment< T >::intersects (const Segment< value_type > & other) const inline
Definition at line 81 of file linearsegment.hh.
Referenced by Rectangle< T >::intersects().
   {
     return getStart () < other.getEnd () && other.getStart () < getEnd () && !isEmpty () && !other.isEmpty ();
   }
template<typename T> bool Segment< T >::isEmpty () const inline
Definition at line 141 of file linearsegment.hh.
Referenced by Segment< value_type >::intersects(), Rectangle< T >::isEmpty(), and Segment< value_type >::operator==().
   {
     return isZero(getSize());
   }
template<typename T> Segment Segment< T >::moveTo (value_type p) const inline
Definition at line 66 of file linearsegment.hh.
Referenced by Rectangle< T >::moveTo().
   {
     return Segment(p, size);
   }
template<typename T> bool Segment< T >::operator!= (const Segment< value_type > & other) const inline
Definition at line 156 of file linearsegment.hh.
   {
     return !(*this == other);
   }
template<typename T> Segment<value_type>& Segment< T >::operator&= (const Segment< value_type > & other) inline
Definition at line 183 of file linearsegment.hh.
   {
     intersect (other);
     return *this;
   }
template<typename T> Segment<value_type>& Segment< T >::operator*= (value_type n) inline
Definition at line 171 of file linearsegment.hh.
   {
     start *= n;
     size *= n;
     return *this;
   }
template<typename T> Segment<value_type>& Segment< T >::operator+= (value_type n) inline
Definition at line 161 of file linearsegment.hh.
   {
     start += n;
     return *this;
   }
template<typename T> Segment<value_type>& Segment< T >::operator-= (value_type n) inline
Definition at line 166 of file linearsegment.hh.
   {
     start -= n;
     return *this;
   }
template<typename T> Segment<value_type>& Segment< T >::operator/= (value_type n) inline
Definition at line 177 of file linearsegment.hh.
   {
     start /= n;
     size /= n;
     return *this;
   }
template<typename T> bool Segment< T >::operator== (const Segment< value_type > & other) const inline
Definition at line 146 of file linearsegment.hh.
   {
     if(isEmpty() != other.isEmpty())
       return false;
     else if(isEmpty())
       return true;
     else
       return areEqual(start, other.start) && areEqual(size, other.size);
   }
template<typename T> void Segment< T >::reduceSizeToMultipleOf (value_type m) inline
Definition at line 86 of file linearsegment.hh.
Referenced by Rectangle< T >::reduceSizeToMultipleOf().
   {
     size -= size % m;
   }
template<typename T> void Segment< T >::setSize (value_type n) inline
Definition at line 188 of file linearsegment.hh.
Referenced by Rectangle< T >::setSize().
   {
     size = n;
   }
Member Data Documentation
template<typename T> value_type Segment< T >::size private
Definition at line 195 of file linearsegment.hh.
Referenced by Segment< value_type >::after(), Segment< value_type >::before(), Segment< value_type >::contains(), Segment< value_type >::getEnd(), Segment< value_type >::getSize(), Segment< value_type >::moveTo(), Segment< value_type >::operator*=(), Segment< value_type >::operator/=(), Segment< value_type >::operator==(), Segment< value_type >::reduceSizeToMultipleOf(), Segment< value_type >::Segment(), and Segment< value_type >::setSize().
template<typename T> value_type Segment< T >::start private
Definition at line 194 of file linearsegment.hh.
Referenced by Segment< value_type >::after(), Segment< value_type >::before(), Segment< value_type >::contains(), Segment< value_type >::getEnd(), Segment< value_type >::getStart(), Segment< value_type >::operator*=(), Segment< value_type >::operator+=(), Segment< value_type >::operator-=(), Segment< value_type >::operator/=(), Segment< value_type >::operator==(), and Segment< value_type >::Segment().
The documentation for this class was generated from the following file:
inc/scroom/linearsegment.hh