Scroom: Rectangle< T > Class Template Reference
Rectangle< T > Class Template Reference
#include <rectangle.hh>
Public Types
typedef T value_type
Public Member Functions
Rectangle ()
Rectangle (value_type x_, value_type y_, value_type width_, value_type height_)
Rectangle (const Segment< value_type > &horizontally_, const Segment< value_type > &vertically_)
Rectangle (const GdkRectangle &rect)
Rectangle (const Rectangle< int > &rect)
GdkRectangle toGdkRectangle () const
Rectangle< int > toIntRectangle () const
Rectangle moveTo (Point< value_type > const &other) const
Rectangle moveTo (value_type const &x, value_type const &y) const
bool contains (Point< value_type > const &other) const
bool contains (const Rectangle &other) const
bool intersects (const Rectangle &other) const
void reduceSizeToMultipleOf (value_type size)
Rectangle intersection (const Rectangle &other) const
value_type getTopPos () const
value_type getLeftPos () const
value_type getBottomPos () const
value_type getRightPos () const
value_type getWidth () const
value_type getHeight () const
Point< value_type > getTopLeft () const
Point< value_type > getTopRight () const
Point< value_type > getBottomLeft () const
Point< value_type > getBottomRight () const
bool isEmpty () const
Rectangle< value_type > leftOf (value_type v) const
Rectangle< value_type > rightOf (value_type v) const
Rectangle< value_type > above (value_type v) const
Rectangle< value_type > below (value_type v) const
Rectangle< value_type > leftOf (Rectangle< value_type > const &r) const
Rectangle< value_type > rightOf (Rectangle< value_type > const &r) const
Rectangle< value_type > above (Rectangle< value_type > const &r) const
Rectangle< value_type > below (Rectangle< value_type > const &r) const
bool operator== (const Rectangle &other) const
bool operator!= (const Rectangle &other) const
Rectangle< value_type > & operator+= (Point< value_type > const &other)
Rectangle< value_type > & operator-= (Point< value_type > const &other)
Rectangle< value_type > & operator*= (value_type other)
Rectangle< value_type > & operator*= (Point< value_type > const &other)
Rectangle< value_type > & operator/= (value_type other)
Rectangle< value_type > & operator/= (Point< value_type > const &other)
const Segment< value_type > & getHorizontally () const
const Segment< value_type > & getVertically () const
void setSize (Point< value_type > const &s)
Private Attributes
Segment< value_type > horizontally
Segment< value_type > vertically
Detailed Description
template<typename T>
class Rectangle< T >
Definition at line 20 of file rectangle.hh.
Member Typedef Documentation
template<typename T> typedef T Rectangle< T >::value_type
Definition at line 28 of file rectangle.hh.
Constructor & Destructor Documentation
template<typename T> Rectangle< T >::Rectangle () inline
Definition at line 30 of file rectangle.hh.
Referenced by Rectangle< T >::intersection(), and Rectangle< T >::moveTo().
   {}
template<typename T> Rectangle< T >::Rectangle (value_type x_, value_type y_, value_type width_, value_type height_) inline
Definition at line 33 of file rectangle.hh.
     : horizontally(x_, width_), vertically(y_, height_)
   {}
template<typename T> Rectangle< T >::Rectangle (const Segment< value_type > & horizontally_, const Segment< value_type > & vertically_) inline
Definition at line 37 of file rectangle.hh.
     : horizontally(horizontally_), vertically(vertically_)
   {}
template<typename T> Rectangle< T >::Rectangle (const GdkRectangle< T > & rect) inline
Definition at line 41 of file rectangle.hh.
     : horizontally(rect.x, rect.width), vertically(rect.y, rect.height)
   {}
template<typename T> Rectangle< T >::Rectangle (const Rectangle< int > & rect) inline
Definition at line 45 of file rectangle.hh.
     : horizontally(rect.getHorizontally()), vertically(rect.getVertically())
   {}
Member Function Documentation
template<typename T> Rectangle<value_type> Rectangle< T >::above (value_type v) const inline
Definition at line 167 of file rectangle.hh.
Referenced by drawOutOfBoundsWithoutBackground().
   {
     return Rectangle<value_type>(horizontally, vertically.before(v));
   }
template<typename T> Rectangle<value_type> Rectangle< T >::above (Rectangle< value_type > const & r) const inline
Definition at line 195 of file rectangle.hh.
   {
     if(r.isEmpty())
       return r;
     return Rectangle<value_type>(horizontally.intersection(r.horizontally),
                                  vertically.before(r.vertically.getStart()));
   }
template<typename T> Rectangle<value_type> Rectangle< T >::below (value_type v) const inline
Definition at line 172 of file rectangle.hh.
Referenced by drawOutOfBoundsWithoutBackground().
   {
     return Rectangle<value_type>(horizontally, vertically.after(v));
   }
template<typename T> Rectangle<value_type> Rectangle< T >::below (Rectangle< value_type > const & r) const inline
Definition at line 204 of file rectangle.hh.
   {
     if(r.isEmpty())
       return r;
     return Rectangle<value_type>(horizontally.intersection(r.horizontally),
                                  vertically.after(r.vertically.getEnd()));
   }
template<typename T> bool Rectangle< T >::contains (Point< value_type > const & other) const inline
Definition at line 69 of file rectangle.hh.
   {
     return
       horizontally.contains(other.x) &&
       vertically.contains(other.y);
   }
template<typename T> bool Rectangle< T >::contains (const Rectangle< T > & other) const inline
Definition at line 76 of file rectangle.hh.
   {
     return
       horizontally.contains(other.horizontally) &&
       vertically.contains(other.vertically);
   }
template<typename T> Point<value_type> Rectangle< T >::getBottomLeft () const inline
Definition at line 142 of file rectangle.hh.
   {
     return Point<value_type>(horizontally.getStart(), vertically.getEnd());
   }
template<typename T> value_type Rectangle< T >::getBottomPos () const inline
Definition at line 112 of file rectangle.hh.
Referenced by drawOutOfBoundsWithoutBackground(), TiledBitmap::redrawZoomingIn(), and TiledBitmap::redrawZoomingOut().
   {
     return vertically.getEnd();
   }
template<typename T> Point<value_type> Rectangle< T >::getBottomRight () const inline
Definition at line 147 of file rectangle.hh.
Referenced by TiledBitmap::redrawZoomingOut().
   {
     return Point<value_type>(horizontally.getEnd(), vertically.getEnd());
   }
template<typename T> value_type Rectangle< T >::getHeight () const inline
Definition at line 127 of file rectangle.hh.
Referenced by setClip(), Rectangle< T >::toGdkRectangle(), and Rectangle< T >::toIntRectangle().
   {
     return vertically.getSize();
   }
template<typename T> const Segment<value_type>& Rectangle< T >::getHorizontally () const inline
Definition at line 268 of file rectangle.hh.
   {
     return horizontally;
   }
template<typename T> value_type Rectangle< T >::getLeftPos () const inline
Definition at line 107 of file rectangle.hh.
Referenced by drawOutOfBoundsWithoutBackground(), operator<<(), TiledBitmap::redrawZoomingIn(), TiledBitmap::redrawZoomingOut(), setClip(), Rectangle< T >::toGdkRectangle(), and Rectangle< T >::toIntRectangle().
   {
     return horizontally.getStart();
   }
template<typename T> value_type Rectangle< T >::getRightPos () const inline
Definition at line 117 of file rectangle.hh.
Referenced by drawOutOfBoundsWithoutBackground(), TiledBitmap::redrawZoomingIn(), and TiledBitmap::redrawZoomingOut().
   {
     return horizontally.getEnd();
   }
template<typename T> Point<value_type> Rectangle< T >::getTopLeft () const inline
Definition at line 132 of file rectangle.hh.
Referenced by drawOutOfBoundsWithBackground(), drawOutOfBoundsWithBackgroundColor(), drawOutOfBoundsWithoutBackground(), and TiledBitmap::redrawZoomingOut().
   {
     return Point<value_type>(horizontally.getStart(), vertically.getStart());
   }
template<typename T> value_type Rectangle< T >::getTopPos () const inline
Definition at line 102 of file rectangle.hh.
Referenced by drawOutOfBoundsWithoutBackground(), TiledBitmap::redrawZoomingIn(), TiledBitmap::redrawZoomingOut(), setClip(), Rectangle< T >::toGdkRectangle(), and Rectangle< T >::toIntRectangle().
   {
     return vertically.getStart();
   }
template<typename T> Point<value_type> Rectangle< T >::getTopRight () const inline
Definition at line 137 of file rectangle.hh.
   {
     return Point<value_type>(horizontally.getEnd(), vertically.getStart());
   }
template<typename T> const Segment<value_type>& Rectangle< T >::getVertically () const inline
Definition at line 273 of file rectangle.hh.
   {
     return vertically;
   }
template<typename T> value_type Rectangle< T >::getWidth () const inline
Definition at line 122 of file rectangle.hh.
Referenced by setClip(), Rectangle< T >::toGdkRectangle(), and Rectangle< T >::toIntRectangle().
   {
     return horizontally.getSize();
   }
template<typename T> Rectangle Rectangle< T >::intersection (const Rectangle< T > & other) const inline
Definition at line 96 of file rectangle.hh.
Referenced by TiledBitmap::redrawZoomingIn(), and TiledBitmap::redrawZoomingOut().
   {
     return Rectangle(horizontally.intersection(other.horizontally),
                      vertically.intersection(other.vertically));
   }
template<typename T> bool Rectangle< T >::intersects (const Rectangle< T > & other) const inline
Definition at line 83 of file rectangle.hh.
   {
     return
       horizontally.intersects(other.horizontally) &&
       vertically.intersects(other.vertically);
   }
template<typename T> bool Rectangle< T >::isEmpty () const inline
Definition at line 152 of file rectangle.hh.
Referenced by Rectangle< T >::above(), Rectangle< T >::below(), Rectangle< T >::leftOf(), Rectangle< T >::operator==(), and Rectangle< T >::rightOf().
   {
     return horizontally.isEmpty() || vertically.isEmpty();
   }
template<typename T> Rectangle<value_type> Rectangle< T >::leftOf (value_type v) const inline
Definition at line 157 of file rectangle.hh.
Referenced by drawOutOfBoundsWithoutBackground().
   {
     return Rectangle<value_type>(horizontally.before(v), vertically);
   }
template<typename T> Rectangle<value_type> Rectangle< T >::leftOf (Rectangle< value_type > const & r) const inline
Definition at line 177 of file rectangle.hh.
   {
     if(r.isEmpty())
       return r;
     return Rectangle<value_type>(horizontally.before(r.horizontally.getStart()),
                                  vertically.intersection(r.vertically));
   }
template<typename T> Rectangle Rectangle< T >::moveTo (Point< value_type > const & other) const inline
Definition at line 59 of file rectangle.hh.
Referenced by drawOutOfBoundsWithBackground().
   {
     return moveTo(other.x, other.y);
   }
template<typename T> Rectangle Rectangle< T >::moveTo (value_type const & x, value_type const & y) const inline
Definition at line 64 of file rectangle.hh.
   {
     return Rectangle(horizontally.moveTo(x), vertically.moveTo(y));
   }
template<typename T> bool Rectangle< T >::operator!= (const Rectangle< T > & other) const inline
Definition at line 223 of file rectangle.hh.
   {
     return !(*this==other);
   }
template<typename T> Rectangle<value_type>& Rectangle< T >::operator*= (value_type other) inline
Definition at line 240 of file rectangle.hh.
   {
     horizontally *= other;
     vertically *= other;
     return *this;
   }
template<typename T> Rectangle<value_type>& Rectangle< T >::operator*= (Point< value_type > const & other) inline
Definition at line 247 of file rectangle.hh.
   {
     horizontally *= other.x;
     vertically *= other.y;
     return *this;
   }
template<typename T> Rectangle<value_type>& Rectangle< T >::operator+= (Point< value_type > const & other) inline
Definition at line 228 of file rectangle.hh.
   {
     horizontally += other.x;
     vertically += other.y;
     return *this;
   }
template<typename T> Rectangle<value_type>& Rectangle< T >::operator-= (Point< value_type > const & other) inline
Definition at line 235 of file rectangle.hh.
   {
     return *this += -other;
   }
template<typename T> Rectangle<value_type>& Rectangle< T >::operator/= (value_type other) inline
Definition at line 254 of file rectangle.hh.
   {
     horizontally /= other;
     vertically /= other;
     return *this;
   }
template<typename T> Rectangle<value_type>& Rectangle< T >::operator/= (Point< value_type > const & other) inline
Definition at line 261 of file rectangle.hh.
   {
     horizontally /= other.x;
     vertically /= other.y;
     return *this;
   }
template<typename T> bool Rectangle< T >::operator== (const Rectangle< T > & other) const inline
Definition at line 213 of file rectangle.hh.
   {
     if(isEmpty() != other.isEmpty())
       return false;
     else if(isEmpty())
       return true;
     else
       return horizontally == other.horizontally && vertically == other.vertically;
   }
template<typename T> void Rectangle< T >::reduceSizeToMultipleOf (value_type size) inline
Definition at line 90 of file rectangle.hh.
   {
     horizontally.reduceSizeToMultipleOf(size);
     vertically.reduceSizeToMultipleOf(size);
   }
template<typename T> Rectangle<value_type> Rectangle< T >::rightOf (value_type v) const inline
Definition at line 162 of file rectangle.hh.
Referenced by drawOutOfBoundsWithoutBackground().
   {
     return Rectangle<value_type>(horizontally.after(v), vertically);
   }
template<typename T> Rectangle<value_type> Rectangle< T >::rightOf (Rectangle< value_type > const & r) const inline
Definition at line 186 of file rectangle.hh.
   {
     if(r.isEmpty())
       return r;
     return Rectangle<value_type>(horizontally.after(r.horizontally.getEnd()),
                                  vertically.intersection(r.vertically));
   }
template<typename T> void Rectangle< T >::setSize (Point< value_type > const & s) inline
Definition at line 278 of file rectangle.hh.
Referenced by TiledBitmap::redrawZoomingOut().
   {
     horizontally.setSize(s.x);
     vertically.setSize(s.y);
   }
template<typename T> GdkRectangle Rectangle< T >::toGdkRectangle () const inline
Definition at line 49 of file rectangle.hh.
Referenced by TransparentOverlayViewInfo::redraw(), TiledBitmap::redrawZoomingIn(), and TiledBitmap::redrawZoomingOut().
   {
     return Scroom::GtkHelpers::createGdkRectangle(getLeftPos(), getTopPos(), getWidth(), getHeight());
   }
template<typename T> Rectangle<int> Rectangle< T >::toIntRectangle () const inline
Definition at line 54 of file rectangle.hh.
Referenced by TiledBitmap::redraw().
   {
     return Rectangle<int>(getLeftPos(), getTopPos(), getWidth(), getHeight());
   }
Member Data Documentation
template<typename T> Segment<value_type> Rectangle< T >::horizontally private
Definition at line 285 of file rectangle.hh.
Referenced by Rectangle< T >::above(), Rectangle< T >::below(), Rectangle< T >::contains(), Rectangle< T >::getBottomLeft(), Rectangle< T >::getBottomRight(), Rectangle< T >::getHorizontally(), Rectangle< T >::getLeftPos(), Rectangle< T >::getRightPos(), Rectangle< T >::getTopLeft(), Rectangle< T >::getTopRight(), Rectangle< T >::getWidth(), Rectangle< T >::intersection(), Rectangle< T >::intersects(), Rectangle< T >::isEmpty(), Rectangle< T >::leftOf(), Rectangle< T >::moveTo(), Rectangle< T >::operator*=(), Rectangle< T >::operator+=(), Rectangle< T >::operator/=(), Rectangle< T >::operator==(), Rectangle< T >::reduceSizeToMultipleOf(), Rectangle< T >::rightOf(), and Rectangle< T >::setSize().
template<typename T> Segment<value_type> Rectangle< T >::vertically private
Definition at line 286 of file rectangle.hh.
Referenced by Rectangle< T >::above(), Rectangle< T >::below(), Rectangle< T >::contains(), Rectangle< T >::getBottomLeft(), Rectangle< T >::getBottomPos(), Rectangle< T >::getBottomRight(), Rectangle< T >::getHeight(), Rectangle< T >::getTopLeft(), Rectangle< T >::getTopPos(), Rectangle< T >::getTopRight(), Rectangle< T >::getVertically(), Rectangle< T >::intersection(), Rectangle< T >::intersects(), Rectangle< T >::isEmpty(), Rectangle< T >::leftOf(), Rectangle< T >::moveTo(), Rectangle< T >::operator*=(), Rectangle< T >::operator+=(), Rectangle< T >::operator/=(), Rectangle< T >::operator==(), Rectangle< T >::reduceSizeToMultipleOf(), Rectangle< T >::rightOf(), and Rectangle< T >::setSize().
The documentation for this class was generated from the following file:
inc/scroom/rectangle.hh