Scroom: libs/scroom/src/cairo-helpers.cc File Reference
cairo-helpers.cc File Reference
#include <scroom/cairo-helpers.hh>
#include <iostream>
#include <boost/assign/list_of.hpp>
Namespaces
Colors
Functions
const Color Colors::OUT_OF_BOUNDS (0.75, 0.75, 1)
void setClip (cairo_t *cr, int x, int y, int width, int height)
void setClip (cairo_t *cr, const GdkRectangle &area)
void drawRectangle (cairo_t *cr, Color const &c, Rectangle< double > const &viewArea)
void drawOutOfBoundsWithBackground (cairo_t *cr, Rectangle< int > const &requestedPresentationArea, Rectangle< int > const &actualPresentationArea, double pixelSize)
void drawOutOfBoundsWithBackgroundColor (cairo_t *cr, const Color &background, Rectangle< int > const &requestedPresentationArea, Rectangle< int > const &actualPresentationArea, double pixelSize)
void drawOutOfBoundsWithoutBackground (cairo_t *cr, Rectangle< int > const &requestedPresentationArea, Rectangle< int > const &actualPresentationArea, double pixelSize)
double pixelSizeFromZoom (int zoom)
Variables
const Color Colors::IN_BOUNDS (1, 1, 1)
Function Documentation
void drawOutOfBoundsWithBackground (cairo_t * cr, Rectangle< int > const & requestedPresentationArea, Rectangle< int > const & actualPresentationArea, double pixelSize)
Definition at line 48 of file cairo-helpers.cc.
 {
   drawRectangle(cr, Colors::OUT_OF_BOUNDS, pixelSize*(requestedPresentationArea.moveTo(0,0)));
   drawRectangle(cr, Colors::IN_BOUNDS,
                 pixelSize*(actualPresentationArea - requestedPresentationArea.getTopLeft()));
 }
void drawOutOfBoundsWithBackgroundColor (cairo_t * cr, const Color & background, Rectangle< int > const & requestedPresentationArea, Rectangle< int > const & actualPresentationArea, double pixelSize)
Definition at line 57 of file cairo-helpers.cc.
 {
   drawOutOfBoundsWithoutBackground(cr, requestedPresentationArea, actualPresentationArea, pixelSize);
   drawRectangle(cr, background,
                 pixelSize*(actualPresentationArea - requestedPresentationArea.getTopLeft()));
 }
void drawOutOfBoundsWithoutBackground (cairo_t * cr, Rectangle< int > const & requestedPresentationArea, Rectangle< int > const & actualPresentationArea, double pixelSize)
Definition at line 66 of file cairo-helpers.cc.
Referenced by drawOutOfBoundsWithBackgroundColor(), and TiffPresentation::redraw().
 {
   std::list<Rectangle<int> > border = boost::assign::list_of
     (requestedPresentationArea.leftOf(actualPresentationArea.getLeftPos()))
     (requestedPresentationArea.rightOf(actualPresentationArea.getRightPos()))
     (requestedPresentationArea.above(actualPresentationArea.getTopPos()))
     (requestedPresentationArea.below(actualPresentationArea.getBottomPos()));
   for(const Rectangle<int>& r: border)
   {
     if(!r.isEmpty())
     {
       drawRectangle(cr, Colors::OUT_OF_BOUNDS, pixelSize*(r - requestedPresentationArea.getTopLeft()));
     }
   }
 }
void drawRectangle (cairo_t * cr, Color const & c, Rectangle< double > const & viewArea)
Definition at line 36 of file cairo-helpers.cc.
Referenced by drawOutOfBoundsWithBackground(), drawOutOfBoundsWithBackgroundColor(), drawOutOfBoundsWithoutBackground(), and CommonOperations::drawState().
 {
   cairo_save(cr);
   c.setColor(cr);
   setClip(cr, viewArea);
   cairo_paint(cr);
   cairo_restore(cr);
 }
double pixelSizeFromZoom (int zoom)
Definition at line 85 of file cairo-helpers.cc.
Referenced by TiffPresentation::redraw().
 {
   double pixelSize=1.0;
   if(zoom >=0)
     pixelSize *= 1<<zoom;
   else
     pixelSize /= 1<<(-zoom);
   return pixelSize;
 }
void setClip (cairo_t * cr, int x, int y, int width, int height)
Definition at line 21 of file cairo-helpers.cc.
Referenced by CommonOperations::draw(), drawRectangle(), and setClip().
 {
   cairo_move_to(cr, x, y);
   cairo_line_to(cr, x+width, y);
   cairo_line_to(cr, x+width, y+height);
   cairo_line_to(cr, x, y+height);
   cairo_line_to(cr, x, y);
   cairo_clip(cr);
 }
void setClip (cairo_t * cr, const GdkRectangle & area)
Definition at line 31 of file cairo-helpers.cc.
 {
   setClip(cr, area.x, area.y, area.width, area.height);
 }