Scroom: CommonOperations Class Reference
CommonOperations Class Reference
#include <layeroperations.hh>
Public Member Functions
virtual ~CommonOperations ()
void drawPixelValue (cairo_t *cr, int x, int y, int size, int value)
void drawPixelValue (cairo_t *cr, int x, int y, int size, int value, Color const &bgColor)
virtual void initializeCairo (cairo_t *cr)
Initialize the canvas for drawing the bitmap.
virtual void drawState (cairo_t *cr, TileState s, GdkRectangle viewArea)
Draw the given state into the given viewArea.
virtual Scroom::Utils::Stuff cacheZoom (const ConstTile::Ptr tile, int zoom, Scroom::Utils::Stuff cache)
Cache data for use during later draw() calls.
virtual void draw (cairo_t *cr, const ConstTile::Ptr tile, GdkRectangle tileArea, GdkRectangle viewArea, int zoom, Scroom::Utils::Stuff cache)
Draw the given tileArea into the given viewArea at the requested zoom level.
Public Member Functions inherited from LayerOperations
virtual ~LayerOperations ()
virtual int getBpp ()=0
Return the number of bits per pixel that the layer will use.
virtual Scroom::Utils::Stuff cache (const ConstTile::Ptr tile)
Cache data for use during later cacheZoom() calls.
virtual void reduce (Tile::Ptr target, const ConstTile::Ptr source, int x, int y)=0
Reduce the source tile by a factor of 8.
Additional Inherited Members
Public Types inherited from LayerOperations
typedef boost::shared_ptr
< LayerOperations > Ptr
Detailed Description
Definition at line 13 of file layeroperations.hh.
Constructor & Destructor Documentation
virtual CommonOperations::~CommonOperations () inline virtual
Definition at line 16 of file layeroperations.hh.
   {}
Member Function Documentation
Scroom::Utils::Stuff CommonOperations::cacheZoom (const ConstTile::Ptr tile, int zoom, Scroom::Utils::Stuff cache) virtual
Cache data for use during later draw() calls.
This function is called for a given tile and zoom level, and then the results are passed to the draw() function. Because draw() is called relatively frequently (i.e. when scrolling), it is recommended to do cpu-intensive work in the cache() and cacheZoom() functions, and then re-use the data to make the draw() faster.
The default implementation returns an empty reference, meaning nothing is cached. As a result, the draw() function will receive an empty reference.
Parameters
tile the Tile for which caching is requested
zoom the requested zoom level
cache the output of cache(const ConstTile::Ptr)
Reimplemented from LayerOperations.
Reimplemented in Operations1bppClipped.
Definition at line 135 of file layeroperations.cc.
 {
   // In: Cairo surface at zoom level 0
   // Out: Cairo surface at requested zoom level
   Scroom::Utils::Stuff result;
   if(zoom>=0)
   {
     // Don't zoom in. It is a waste of space
     result = cache;
   }
   else if (!cache)
   {
     printf("PANIC: Base caching failed to return anything\n");
   }
   else
   {
     int divider = 1<<-zoom;
     BitmapSurface::Ptr source = boost::static_pointer_cast<BitmapSurface>(cache);
     BitmapSurface::Ptr target = BitmapSurface::create(tile->width/divider, tile->height/divider,
                                                       CAIRO_FORMAT_ARGB32);
     result = target;
     cairo_surface_t* surface = target->get();
     cairo_t* cr = cairo_create(surface);
     initializeCairo(cr);
     cairo_scale(cr, 1.0/divider, 1.0/divider);
     cairo_set_source_surface(cr, source->get(), 0, 0);
     cairo_paint(cr);
     cairo_destroy(cr);
   }
   return result;
 }
void CommonOperations::draw (cairo_t * cr, const ConstTile::Ptr tile, GdkRectangle tileArea, GdkRectangle viewArea, int zoom, Scroom::Utils::Stuff cache) virtual
Draw the given tileArea into the given viewArea at the requested zoom level.
Parameters
cr The canvas on which to draw
tile The tile to take data from
tileArea Area of the tile that needs to be drawn
viewArea Area of the canvas that the tile needs to be drawn in
zoom The requested zoom level. One pixel of your presentation should have size 2**zoom when drawn. zoom will be negative for all but the first layer.
cache Depending on whether the cache() function finished already, this may either be an empty reference, or a reference to the value returned by cache()
Implements LayerOperations.
Reimplemented in Operations, Operations8bpp, and Operations1bpp.
Definition at line 171 of file layeroperations.cc.
Referenced by Operations1bpp::draw(), Operations8bpp::draw(), and Operations::draw().
 {
   // In: Cairo surface at requested zoom level
   // Out: given surface rendered to the canvas
   UNUSED(tile);
   setClip(cr, viewArea);
   if(!cache)
   {
     drawState(cr, TILE_UNLOADED, viewArea);
   }
   else
   {
     BitmapSurface::Ptr source = boost::static_pointer_cast<BitmapSurface>(cache);
     if(zoom>0)
     {
       // Ask Cairo to zoom in for us
       int multiplier = 1<<zoom;
       int x = viewArea.x / multiplier - tileArea.x;
       int y = viewArea.y / multiplier - tileArea.y;
       cairo_scale(cr, multiplier, multiplier);
       cairo_set_source_surface(cr, source->get(), x, y);
       cairo_pattern_set_filter (cairo_get_source (cr), CAIRO_FILTER_NEAREST);
       cairo_paint(cr);
     }
     else
     {
       // Cached bitmap is to scale
       int divider = 1<<-zoom;
       int x = viewArea.x - tileArea.x / divider;
       int y = viewArea.y - tileArea.y / divider;
       cairo_set_source_surface(cr, source->get(), x, y);
       cairo_paint(cr);
     }
   }
 }
void CommonOperations::drawPixelValue (cairo_t * cr, int x, int y, int size, int value)
Definition at line 104 of file layeroperations.cc.
Referenced by Operations1bpp::draw(), Operations8bpp::draw(), and Operations::draw().
 {
   std::ostringstream s;
   s << value;
   std::string v = s.str();
   const char* cstr = v.c_str();
   cairo_move_to(cr, x, y);
   cairo_line_to(cr, x+size, y);
   cairo_line_to(cr, x+size, y+size);
   cairo_line_to(cr, x, y+size);
   cairo_line_to(cr, x, y);
   cairo_clip(cr);
   // cairo_stroke(cr);
   cairo_text_extents_t extents;
   cairo_text_extents(cr, cstr, &extents);
   double xx = x+size/2-(extents.width/2 + extents.x_bearing);
   double yy = y+size/2-(extents.height/2 + extents.y_bearing);
   cairo_move_to(cr, xx, yy);
   cairo_show_text(cr, cstr);
 }
void CommonOperations::drawPixelValue (cairo_t * cr, int x, int y, int size, int value, Color const & bgColor)
Definition at line 129 of file layeroperations.cc.
 {
   bgColor.getContrastingBlackOrWhite().setColor(cr);
   drawPixelValue(cr, x, y, size, value);
 }
void CommonOperations::drawState (cairo_t * cr, TileState s, GdkRectangle viewArea) virtual
Draw the given state into the given viewArea.
The associated tile is likely not loaded or not initialized or in whatever other TileState that doesn't allow its contents to be drawn.
Something needs to be drawn in the given viewArea anyway. Implementors might want to just draw an empty rectangle, maybe color-coded to reflect the state of the tile.
Implements LayerOperations.
Definition at line 80 of file layeroperations.cc.
 {
   Color c;
   switch(s)
   {
   case TILE_UNINITIALIZED:
     c = Color(1, 1, 0.5); // Yellow
     break;
   case TILE_UNLOADED:
     c = Color(0.5, 1, 0.5); // Green
     break;
   case TILE_LOADED:
     c = Color(1, 0.5, 0.5); // Red
     break;
   case TILE_OUT_OF_BOUNDS:
   default:
     c = Colors::OUT_OF_BOUNDS;
     break;
   }
   drawRectangle(cr, c, viewArea);
 }
void CommonOperations::initializeCairo (cairo_t * cr) virtual
Initialize the canvas for drawing the bitmap.
When TiledBitmapInterface::redraw() is called, (a portion of) the Layer needs to be redrawn. TiledBitmap will compute which tiles are involved in the redraw, and call draw() or drawState() for each of them, as appropriate. However, before doing so, it will first call initializeCairo(). You can take this opportunity to set various properties that are needed in all subsequent calls to draw() and drawState(), such as anti-aliasing and line caps.
Implements LayerOperations.
Definition at line 74 of file layeroperations.cc.
 {
   cairo_set_antialias(cr, CAIRO_ANTIALIAS_NONE);
   cairo_set_line_cap(cr, CAIRO_LINE_CAP_SQUARE);
 }
The documentation for this class was generated from the following files:
inc/scroom/layeroperations.hh
libs/tiled-bitmap/src/layeroperations.cc