Scroom: Viewable Class Reference
Viewable Class Reference abstract
Implement Viewable if you want to be able to receive events when a View is created and/or deleted.
#include <presentationinterface.hh>
Public Types
typedef boost::shared_ptr< Viewable > Ptr
typedef boost::weak_ptr< Viewable > WeakPtr
Public Member Functions
virtual ~Viewable ()
virtual void open (ViewInterface::WeakPtr vi)=0
Gets called just after the View is created.
virtual void close (ViewInterface::WeakPtr vi)=0
Gets called just before the View is destroyed.
Detailed Description
Implement Viewable if you want to be able to receive events when a View is created and/or deleted.
You'll want to receive these events if you either want to influence something on-screen (PresentationInterface, ColormapProvider), or want to store data related to a View (TiledBitmapInterface).
Definition at line 30 of file presentationinterface.hh.
Member Typedef Documentation
Ptr
typedef boost::shared_ptr<Viewable> Viewable::Ptr
Definition at line 33 of file presentationinterface.hh.
WeakPtr
typedef boost::weak_ptr<Viewable> Viewable::WeakPtr
Definition at line 34 of file presentationinterface.hh.
Constructor & Destructor Documentation
~Viewable()
virtual Viewable::~Viewable () inline virtual
Definition at line 37 of file presentationinterface.hh.
 {}
Member Function Documentation
close()
virtual void Viewable::close (ViewInterface::WeakPtr vi) pure virtual
Gets called just before the View is destroyed.
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implemented in Layer, CompressedTile, PresentationBase, TiledBitmap, and TransformPresentation.
Referenced by PresentationMock::create(), and ~Viewable().
open()
virtual void Viewable::open (ViewInterface::WeakPtr vi) pure virtual
Gets called just after the View is created.
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implemented in Layer, CompressedTile, PresentationBase, TiledBitmap, and TransformPresentation.
Referenced by PresentationMock::create(), and ~Viewable().
The documentation for this class was generated from the following file:
inc/scroom/presentationinterface.hh