Scroom: ViewInterface Class Reference
ViewInterface Class Reference abstract
Interface provided to something Viewable.
#include <viewinterface.hh>
Public Types
typedef boost::shared_ptr< ViewInterface > Ptr
typedef boost::weak_ptr< ViewInterface > WeakPtr
Public Member Functions
virtual ~ViewInterface ()
virtual void invalidate ()=0
Request that the window content is redrawn.
virtual ProgressInterface::Ptr getProgressInterface ()=0
Return a pointer to the progess interface associated with the View.
virtual void addSideWidget (std::string title, GtkWidget *w)=0
Request that the given widget be added to the sidebar.
virtual void removeSideWidget (GtkWidget *w)=0
Request that the given widget be removed from the sidebar.
virtual void addToToolbar (GtkToolItem *ti)=0
Request that the given tool item be added to the toolbar.
virtual void removeFromToolbar (GtkToolItem *ti)=0
Request that the given tool item be removed from the toolbar.
Detailed Description
Interface provided to something Viewable.
Internally, scroom uses a View to represent the fact that something (typically a presentation) is visible on the screen. Being a presentation, you typically want to influence whatever is being shown. This interface allows you to do so.
See also
PresentationInterface, Viewable
Definition at line 29 of file viewinterface.hh.
Member Typedef Documentation
Ptr
typedef boost::shared_ptr<ViewInterface> ViewInterface::Ptr
Definition at line 32 of file viewinterface.hh.
WeakPtr
typedef boost::weak_ptr<ViewInterface> ViewInterface::WeakPtr
Definition at line 33 of file viewinterface.hh.
Constructor & Destructor Documentation
~ViewInterface()
virtual ViewInterface::~ViewInterface () inline virtual
Definition at line 36 of file viewinterface.hh.
 {}
Member Function Documentation
addSideWidget()
virtual void ViewInterface::addSideWidget (std::string title, GtkWidget * w) pure virtual
Request that the given widget be added to the sidebar.
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implemented in View, and ChildView.
Referenced by ~ViewInterface().
addToToolbar()
virtual void ViewInterface::addToToolbar (GtkToolItem * ti) pure virtual
Request that the given tool item be added to the toolbar.
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implemented in View, and ChildView.
Referenced by ~ViewInterface().
getProgressInterface()
virtual ProgressInterface::Ptr ViewInterface::getProgressInterface () pure virtual
Return a pointer to the progess interface associated with the View.
Note
The progress bar should only be manipulated from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implemented in View, and ChildView.
Referenced by ~ViewInterface().
invalidate()
virtual void ViewInterface::invalidate () pure virtual
Request that the window content is redrawn.
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implemented in View, and ChildView.
Referenced by ~ViewInterface().
removeFromToolbar()
virtual void ViewInterface::removeFromToolbar (GtkToolItem * ti) pure virtual
Request that the given tool item be removed from the toolbar.
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implemented in View, and ChildView.
Referenced by ~ViewInterface().
removeSideWidget()
virtual void ViewInterface::removeSideWidget (GtkWidget * w) pure virtual
Request that the given widget be removed from the sidebar.
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implemented in View, and ChildView.
Referenced by ~ViewInterface().
The documentation for this class was generated from the following file:
inc/scroom/viewinterface.hh