Scroom: PresentationInterface Class Reference
PresentationInterface Class Reference abstract
Represent some 2D content.
#include <presentationinterface.hh>
Public Types
typedef boost::shared_ptr< PresentationInterface > Ptr
typedef boost::weak_ptr< PresentationInterface > WeakPtr
Public Types inherited from Viewable
typedef boost::shared_ptr< Viewable > Ptr
typedef boost::weak_ptr< Viewable > WeakPtr
Public Types inherited from Scroom::Utils::Observable< T >
typedef boost::shared_ptr< T > Observer
typedef boost::shared_ptr< Observable< T > > Ptr
Public Member Functions
virtual Scroom::Utils::Rectangle< double > getRect ()=0
Return the dimensions of your presentation.
virtual void redraw (ViewInterface::Ptr const &vi, cairo_t *cr, Scroom::Utils::Rectangle< double > presentationArea, int zoom)=0
Draw the requested ara at the requested zoom level.
virtual bool getProperty (const std::string &name, std::string &value)=0
Return the value of the requested property.
virtual bool isPropertyDefined (const std::string &name)=0
Return true if the named property exists.
virtual std::string getTitle ()=0
Return the title of the presentation.
Public Member Functions inherited from Viewable
virtual ~Viewable ()
virtual void open (ViewInterface::WeakPtr vi)=0
Gets called just after the View is created.
virtual void close (ViewInterface::WeakPtr vi)=0
Gets called just before the View is destroyed.
Public Member Functions inherited from Scroom::Utils::Observable< T >
Observable ()
virtual ~Observable ()
Scroom::Bookkeeping::Token registerStrongObserver (Observer const &observer)
Scroom::Bookkeeping::Token registerObserver (ObserverWeak const &observer)
Public Member Functions inherited from Scroom::Utils::Base
virtual ~Base ()
template<typename R >
boost::shared_ptr< R > shared_from_this ()
Calls shared_from_this() with a built-in dynamic cast, to make it usable in subclasses.
template<typename R >
boost::shared_ptr< R const > shared_from_this () const
Calls shared_from_this() with a built-in dynamic cast, to make it usable in subclasses.
Additional Inherited Members
Protected Member Functions inherited from Scroom::Utils::Observable< T >
std::list< Observer > getObservers ()
Retrieve a list of current observers.
virtual void observerAdded (Observer const &observer, Scroom::Bookkeeping::Token const &token)
Override this function if you want to be notified of new observers registering.
Detailed Description
Represent some 2D content.
Anything that should be shown by Scroom in a window should implement this interface.
Objects implementing this interface are typically returned by NewPresentationInterface::createNew() and OpenPresentationInterface::open().
Definition at line 69 of file presentationinterface.hh.
Member Typedef Documentation
Ptr
typedef boost::shared_ptr<PresentationInterface> PresentationInterface::Ptr
Definition at line 72 of file presentationinterface.hh.
WeakPtr
typedef boost::weak_ptr<PresentationInterface> PresentationInterface::WeakPtr
Definition at line 73 of file presentationinterface.hh.
Member Function Documentation
getProperty()
virtual bool PresentationInterface::getProperty (const std::string & name, std::string & value) pure virtual
Return the value of the requested property.
Parameters
[in] name The name of the requested property
[out] value The value of the requested property
Return values
true if the property existed
false if the property didn't exist
Implemented in TiffPresentationWrapper, TransformPresentation, and TransparentOverlayPresentation.
Referenced by PresentationMock::create().
getRect()
virtual Scroom::Utils::Rectangle<double> PresentationInterface::getRect () pure virtual
Return the dimensions of your presentation.
Implemented in TiffPresentationWrapper, TransformPresentation, and TransparentOverlayPresentation.
Referenced by PresentationMock::create().
getTitle()
virtual std::string PresentationInterface::getTitle () pure virtual
Return the title of the presentation.
Implemented in TiffPresentationWrapper, TransformPresentation, and TransparentOverlayPresentation.
Referenced by PresentationMock::create().
isPropertyDefined()
virtual bool PresentationInterface::isPropertyDefined (const std::string & name) pure virtual
Return true if the named property exists.
Implemented in TiffPresentationWrapper, TransformPresentation, and TransparentOverlayPresentation.
Referenced by PresentationMock::create().
redraw()
virtual void PresentationInterface::redraw (ViewInterface::Ptr const & vi, cairo_t * cr, Scroom::Utils::Rectangle< double > presentationArea, int zoom) pure virtual
Draw the requested ara at the requested zoom level.
Parameters
vi The ViewInterface on whose behalf the request is made
cr The context to draw the area on
presentationArea the area that is to be drawn. The given x and y coordinates should map on 0,0 of the given context cr.
zoom The requested zoom level. One pixel of your presentation should have size 2**zoom when drawn. zoom may be negative.
Implemented in TiffPresentationWrapper, TransformPresentation, and TransparentOverlayPresentation.
Referenced by PresentationMock::create().
The documentation for this class was generated from the following file:
inc/scroom/presentationinterface.hh