Scroom: Scroom::Utils::ProgressInterfaceFromProgressStateInterface Class Reference
Scroom::Utils::ProgressInterfaceFromProgressStateInterface Class Reference
#include <progressinterfacehelpers.hh>
Public Member Functions
virtual void setIdle ()
virtual void setWaiting (double progress=0.0)
virtual void setWorking (double progress)
virtual void setFinished ()
Public Member Functions inherited from ProgressInterface
virtual ~ProgressInterface ()
Additional Inherited Members
Public Types inherited from ProgressInterface
typedef boost::shared_ptr< ProgressInterface > Ptr
typedef boost::weak_ptr< ProgressInterface > WeakPtr
Protected Types inherited from Scroom::Utils::ProgressStateInterface
enum State { IDLE, WAITING, WORKING, FINISHED }
typedef boost::shared_ptr< ProgressStateInterface > Ptr
typedef boost::weak_ptr< ProgressStateInterface > WeakPtr
Protected Member Functions inherited from Scroom::Utils::ProgressStateInterface
virtual ~ProgressStateInterface ()
virtual void setProgress (State s, double progress=0.0)=0
Detailed Description
Definition at line 44 of file progressinterfacehelpers.hh.
Member Function Documentation
setFinished()
void Scroom::Utils::ProgressInterfaceFromProgressStateInterface::setFinished () virtual
Implements ProgressInterface.
Definition at line 35 of file progressinterfacehelpers.cc.
Referenced by Scroom::Utils::ProgressStateInterfaceFromProgressInterface::setProgress().
     {
       setProgress(FINISHED, 1.0);
     }
setIdle()
void Scroom::Utils::ProgressInterfaceFromProgressStateInterface::setIdle () virtual
Implements ProgressInterface.
Definition at line 20 of file progressinterfacehelpers.cc.
Referenced by Scroom::Utils::ProgressStateInterfaceFromProgressInterface::setProgress().
     {
       setProgress(IDLE);
     }
setWaiting()
void Scroom::Utils::ProgressInterfaceFromProgressStateInterface::setWaiting (double progress = 0.0) virtual
Implements ProgressInterface.
Definition at line 25 of file progressinterfacehelpers.cc.
Referenced by Scroom::Utils::ProgressStateInterfaceFromProgressInterface::setProgress().
     {
       setProgress(WAITING, progress);
     }
setWorking()
void Scroom::Utils::ProgressInterfaceFromProgressStateInterface::setWorking (double progress) virtual
Implements ProgressInterface.
Definition at line 30 of file progressinterfacehelpers.cc.
Referenced by Scroom::Utils::ProgressStateInterfaceFromProgressInterface::setProgress().
     {
       setProgress(WORKING, progress);
     }
The documentation for this class was generated from the following files:
inc/scroom/progressinterfacehelpers.hh
libs/util/src/progressinterfacehelpers.cc