Scroom: Scroom::Utils::ProgressStateInterface Class Reference
Scroom::Utils::ProgressStateInterface Class Reference abstract
Alternative interface used for reporting progress information.
#include <progressinterfacehelpers.hh>
Public Types
enum State { IDLE, WAITING, WORKING, FINISHED }
typedef boost::shared_ptr< ProgressStateInterface > Ptr
typedef boost::weak_ptr< ProgressStateInterface > WeakPtr
Public Member Functions
virtual ~ProgressStateInterface ()
virtual void setProgress (State s, double progress=0.0)=0
Detailed Description
Alternative interface used for reporting progress information.
Definition at line 25 of file progressinterfacehelpers.hh.
Member Typedef Documentation
Ptr
typedef boost::shared_ptr<ProgressStateInterface> Scroom::Utils::ProgressStateInterface::Ptr
Definition at line 28 of file progressinterfacehelpers.hh.
WeakPtr
typedef boost::weak_ptr<ProgressStateInterface> Scroom::Utils::ProgressStateInterface::WeakPtr
Definition at line 29 of file progressinterfacehelpers.hh.
Member Enumeration Documentation
State
enum Scroom::Utils::ProgressStateInterface::State
Enumerator
IDLE
WAITING
WORKING
FINISHED
Definition at line 31 of file progressinterfacehelpers.hh.
         {
           IDLE,
           WAITING,
           WORKING,
           FINISHED
         } State;
Constructor & Destructor Documentation
~ProgressStateInterface()
virtual Scroom::Utils::ProgressStateInterface::~ProgressStateInterface () inline virtual
Definition at line 39 of file progressinterfacehelpers.hh.
 {}
Member Function Documentation
setProgress()
virtual void Scroom::Utils::ProgressStateInterface::setProgress (State s, double progress = 0.0) pure virtual
Implemented in Scroom::Utils::ProgressInterfaceMultiplexer::Child, Scroom::Utils::ProgressInterfaceMultiplexer::ChildData, Scroom::Utils::Detail::ProgressStore, Scroom::Utils::ProgressStateInterfaceFromProgressInterface, and Scroom::Utils::ProgressInterfaceFromProgressStateInterfaceForwarder.
Referenced by Scroom::Utils::ProgressInterfaceFromProgressStateInterface::setFinished(), Scroom::Utils::ProgressInterfaceFromProgressStateInterface::setIdle(), Scroom::Utils::ProgressInterfaceFromProgressStateInterface::setWaiting(), Scroom::Utils::ProgressInterfaceFromProgressStateInterface::setWorking(), and ~ProgressStateInterface().
The documentation for this class was generated from the following file:
inc/scroom/progressinterfacehelpers.hh