Scroom: ProgressInterface Class Reference
ProgressInterface Class Reference abstract
Interface used for reporting progress information.
#include <progressinterface.hh>
Public Types
typedef boost::shared_ptr
< ProgressInterface > Ptr
typedef boost::weak_ptr
< ProgressInterface > WeakPtr
Public Member Functions
virtual ~ProgressInterface ()
virtual void setIdle ()=0
virtual void setWaiting (double progress=0.0)=0
virtual void setWorking (double progress)=0
virtual void setFinished ()=0
Detailed Description
Interface used for reporting progress information.
Definition at line 15 of file progressinterface.hh.
Member Typedef Documentation
typedef boost::shared_ptr<ProgressInterface> ProgressInterface::Ptr
Definition at line 18 of file progressinterface.hh.
typedef boost::weak_ptr<ProgressInterface> ProgressInterface::WeakPtr
Definition at line 19 of file progressinterface.hh.
Constructor & Destructor Documentation
virtual ProgressInterface::~ProgressInterface () inline virtual
Definition at line 21 of file progressinterface.hh.
 {}
Member Function Documentation
virtual void ProgressInterface::setFinished () pure virtual
Implemented in Scroom::Utils::ProgressInterfaceBroadcaster, Scroom::Utils::ProgressStateInterfaceFromProgressInterfaceForwarder, TiledBitmapViewData, Scroom::Utils::ProgressInterfaceFromProgressStateInterface, and ProgressBarManager.
Referenced by Scroom::Utils::ProgressStateInterfaceFromProgressInterface::setProgress().
virtual void ProgressInterface::setIdle () pure virtual
Implemented in Scroom::Utils::ProgressInterfaceBroadcaster, Scroom::Utils::ProgressStateInterfaceFromProgressInterfaceForwarder, TiledBitmapViewData, Scroom::Utils::ProgressInterfaceFromProgressStateInterface, and ProgressBarManager.
Referenced by Scroom::Utils::ProgressStateInterfaceFromProgressInterface::setProgress().
virtual void ProgressInterface::setWaiting (double progress = 0.0) pure virtual
Implemented in Scroom::Utils::ProgressInterfaceBroadcaster, Scroom::Utils::ProgressStateInterfaceFromProgressInterfaceForwarder, TiledBitmapViewData, Scroom::Utils::ProgressInterfaceFromProgressStateInterface, and ProgressBarManager.
Referenced by Scroom::Utils::ProgressStateInterfaceFromProgressInterface::setProgress().
virtual void ProgressInterface::setWorking (double progress) pure virtual
Implemented in Scroom::Utils::ProgressInterfaceBroadcaster, Scroom::Utils::ProgressStateInterfaceFromProgressInterfaceForwarder, TiledBitmapViewData, Scroom::Utils::ProgressInterfaceFromProgressStateInterface, and ProgressBarManager.
Referenced by Scroom::Utils::ProgressStateInterfaceFromProgressInterface::setProgress().
The documentation for this class was generated from the following file:
inc/scroom/progressinterface.hh