Scroom: FileOperation Class Reference
FileOperation Class Reference abstract
#include <tiled-bitmap.hh>
Public Types
typedef boost::shared_ptr< FileOperation > Ptr
Public Member Functions
virtual ~FileOperation ()
virtual void doneWaiting ()
virtual void finished ()=0
virtual void operator() ()=0
virtual void abort ()=0
Protected Member Functions
FileOperation (ProgressInterface::Ptr progress)
Private Attributes
ProgressInterface::Ptr progress
boost::mutex waitingMutex
bool waiting
Detailed Description
Definition at line 29 of file tiled-bitmap.hh.
Member Typedef Documentation
Ptr
typedef boost::shared_ptr<FileOperation> FileOperation::Ptr
Definition at line 32 of file tiled-bitmap.hh.
Constructor & Destructor Documentation
FileOperation()
FileOperation::FileOperation (ProgressInterface::Ptr progress) protected
Definition at line 58 of file tiled-bitmap.cc.
   : progress(progress), waitingMutex(), waiting(true)
 {
   progress->setWaiting();
 }
~FileOperation()
virtual FileOperation::~FileOperation () inline virtual
Definition at line 42 of file tiled-bitmap.hh.
 {}
Member Function Documentation
abort()
virtual void FileOperation::abort () pure virtual
Implemented in LoadOperation.
Referenced by ~FileOperation(), and LoadOperation::~LoadOperation().
doneWaiting()
void FileOperation::doneWaiting () virtual
Definition at line 64 of file tiled-bitmap.cc.
Referenced by LoadOperation::operator()(), and ~FileOperation().
 {
   boost::mutex::scoped_lock lock(waitingMutex);
   if(waiting)
   {
     gdk_threads_enter();
     progress->setWorking(0);
     gdk_threads_leave();
     waiting = false;
   }
 }
finished()
virtual void FileOperation::finished () pure virtual
Implemented in LoadOperation.
Referenced by ~FileOperation(), and LoadOperation::~LoadOperation().
operator()()
virtual void FileOperation::operator() () pure virtual
Implemented in LoadOperation.
Referenced by ~FileOperation(), and LoadOperation::~LoadOperation().
Member Data Documentation
progress
ProgressInterface::Ptr FileOperation::progress private
Definition at line 34 of file tiled-bitmap.hh.
Referenced by doneWaiting().
waiting
bool FileOperation::waiting private
Definition at line 36 of file tiled-bitmap.hh.
Referenced by doneWaiting().
waitingMutex
boost::mutex FileOperation::waitingMutex private
Definition at line 35 of file tiled-bitmap.hh.
Referenced by doneWaiting().
The documentation for this class was generated from the following files:
libs/tiled-bitmap/src/tiled-bitmap.hh
libs/tiled-bitmap/src/tiled-bitmap.cc