Scroom: LayerOperations Class Reference
LayerOperations Class Reference abstract
Operations on a layer in the TiledBitmap.
#include <tiledbitmapinterface.hh>
Public Types
typedef boost::shared_ptr< LayerOperations > Ptr
Public Member Functions
virtual ~LayerOperations ()
virtual int getBpp ()=0
Return the number of bits per pixel that the layer will use.
virtual void initializeCairo (cairo_t *cr)=0
Initialize the canvas for drawing the bitmap.
virtual void draw (cairo_t *cr, const ConstTile::Ptr tile, Scroom::Utils::Rectangle< double > tileArea, Scroom::Utils::Rectangle< double > viewArea, int zoom, Scroom::Utils::Stuff cache)=0
Draw the given tileArea into the given viewArea at the requested zoom level.
virtual void drawState (cairo_t *cr, TileState s, Scroom::Utils::Rectangle< double > viewArea)=0
Draw the given state into the given viewArea.
virtual Scroom::Utils::Stuff cache (const ConstTile::Ptr tile)
Cache data for use during later cacheZoom() calls.
virtual Scroom::Utils::Stuff cacheZoom (const ConstTile::Ptr tile, int zoom, Scroom::Utils::Stuff cache)
Cache data for use during later draw() calls.
virtual void reduce (Tile::Ptr target, const ConstTile::Ptr source, int x, int y)=0
Reduce the source tile by a factor of 8.
Detailed Description
Operations on a layer in the TiledBitmap.
Tasks of LayerOperations objects include:
Reducing the given Layer by a factor of 8, producing data that the LayerOperations object of the next layer will understand
Draw any portion of the given Layer, at the requested zoom level
See also
Layer
Definition at line 49 of file tiledbitmapinterface.hh.
Member Typedef Documentation
Ptr
typedef boost::shared_ptr<LayerOperations> LayerOperations::Ptr
Definition at line 52 of file tiledbitmapinterface.hh.
Constructor & Destructor Documentation
~LayerOperations()
virtual LayerOperations::~LayerOperations () inline virtual
Definition at line 55 of file tiledbitmapinterface.hh.
   {
   }
Member Function Documentation
cache()
virtual Scroom::Utils::Stuff LayerOperations::cache (const ConstTile::Ptr tile) inline virtual
Cache data for use during later cacheZoom() calls.
This function is called for a given tile, and then the results are passed to the cacheZoom() function. Because draw() is called relatively frequently (i.e. when scrolling), it is recommended to do cpu-intensive work in the cache() and cacheZoom() functions, and then re-use the data to make the draw() faster.
The default implementation returns an empty reference, meaning nothing is cached. As a result, the draw() function will receive an empty reference.
Parameters
tile the Tile for which caching is requested
Reimplemented in OperationsColormapped, Operations, Operations24bpp, Operations8bpp, and Operations1bpp.
Definition at line 126 of file tiledbitmapinterface.hh.
Referenced by CommonOperations::~CommonOperations(), ~LayerOperations(), Operations::~Operations(), Operations1bpp::~Operations1bpp(), Operations1bppClipped::~Operations1bppClipped(), Operations24bpp::~Operations24bpp(), Operations8bpp::~Operations8bpp(), and OperationsColormapped::~OperationsColormapped().
   {
     UNUSED(tile);
     return Scroom::Utils::Stuff();
   }
cacheZoom()
virtual Scroom::Utils::Stuff LayerOperations::cacheZoom (const ConstTile::Ptr tile, int zoom, Scroom::Utils::Stuff cache) inline virtual
Cache data for use during later draw() calls.
This function is called for a given tile and zoom level, and then the results are passed to the draw() function. Because draw() is called relatively frequently (i.e. when scrolling), it is recommended to do cpu-intensive work in the cache() and cacheZoom() functions, and then re-use the data to make the draw() faster.
The default implementation returns an empty reference, meaning nothing is cached. As a result, the draw() function will receive an empty reference.
Parameters
tile the Tile for which caching is requested
zoom the requested zoom level
cache the output of cache(const ConstTile::Ptr)
Reimplemented in Operations1bppClipped, and CommonOperations.
Definition at line 150 of file tiledbitmapinterface.hh.
   {
     UNUSED(tile);
     UNUSED(zoom);
     UNUSED(cache);
     return Scroom::Utils::Stuff();
   }
draw()
virtual void LayerOperations::draw (cairo_t * cr, const ConstTile::Ptr tile, Scroom::Utils::Rectangle< double > tileArea, Scroom::Utils::Rectangle< double > viewArea, int zoom, Scroom::Utils::Stuff cache) pure virtual
Draw the given tileArea into the given viewArea at the requested zoom level.
Parameters
cr The canvas on which to draw
tile The tile to take data from
tileArea Area of the tile that needs to be drawn
viewArea Area of the canvas that the tile needs to be drawn in
zoom The requested zoom level. One pixel of your presentation should have size 2**zoom when drawn. zoom will be negative for all but the first layer.
cache Depending on whether the cache() function finished already, this may either be an empty reference, or a reference to the value returned by cache()
Implemented in Operations, Operations8bpp, Operations1bpp, and CommonOperations.
Referenced by ~LayerOperations().
drawState()
virtual void LayerOperations::drawState (cairo_t * cr, TileState s, Scroom::Utils::Rectangle< double > viewArea) pure virtual
Draw the given state into the given viewArea.
The associated tile is likely not loaded or not initialized or in whatever other TileState that doesn't allow its contents to be drawn.
Something needs to be drawn in the given viewArea anyway. Implementors might want to just draw an empty rectangle, maybe color-coded to reflect the state of the tile.
Implemented in CommonOperations.
Referenced by ~LayerOperations().
getBpp()
virtual int LayerOperations::getBpp () pure virtual
Return the number of bits per pixel that the layer will use.
This number will be used to compute the amount of memory required to store one tile
Implemented in Operations1bppClipped, OperationsColormapped, Operations, Operations24bpp, Operations8bpp, and Operations1bpp.
Referenced by ~LayerOperations(), Operations::~Operations(), Operations1bpp::~Operations1bpp(), Operations1bppClipped::~Operations1bppClipped(), Operations24bpp::~Operations24bpp(), Operations8bpp::~Operations8bpp(), and OperationsColormapped::~OperationsColormapped().
initializeCairo()
virtual void LayerOperations::initializeCairo (cairo_t * cr) pure virtual
Initialize the canvas for drawing the bitmap.
When TiledBitmapInterface::redraw() is called, (a portion of) the Layer needs to be redrawn. TiledBitmap will compute which tiles are involved in the redraw, and call draw() or drawState() for each of them, as appropriate. However, before doing so, it will first call initializeCairo(). You can take this opportunity to set various properties that are needed in all subsequent calls to draw() and drawState(), such as anti-aliasing and line caps.
Implemented in CommonOperations.
Referenced by ~LayerOperations().
reduce()
virtual void LayerOperations::reduce (Tile::Ptr target, const ConstTile::Ptr source, int x, int y) pure virtual
Reduce the source tile by a factor of 8.
The target tile will contain data for 8*8 source tiles. Offsets x and y indicate which of those 64 source tiles is currently being processed
Parameters
target Tile that will contain the reduced bitmap
source Tile that is to be reduced
x x-offset (0..7) of the source tile in the target tile
y y-offset (0..7) of the source tile in the target tile
Note
The target tile belongs to a different layer, and hence possibly has a different bpp than the current one, depending on the LayerSpec given to createTiledBitmap()
Implemented in Operations1bppClipped, OperationsColormapped, Operations, Operations24bpp, Operations8bpp, and Operations1bpp.
Referenced by cacheZoom(), Operations::~Operations(), Operations1bpp::~Operations1bpp(), Operations1bppClipped::~Operations1bppClipped(), Operations24bpp::~Operations24bpp(), Operations8bpp::~Operations8bpp(), and OperationsColormapped::~OperationsColormapped().
The documentation for this class was generated from the following file:
inc/scroom/tiledbitmapinterface.hh