Scroom: Scroom::Utils::Detail::Registration< T > Class Template Reference
Scroom::Utils::Detail::Registration< T > Class Template Reference
Contain all info regarding the registration.
#include <observable.hh>
Public Types
typedef boost::shared_ptr< Registration > Ptr
Public Member Functions
Registration ()
Registration (boost::weak_ptr< Observable< T > > observable, boost::shared_ptr< T > observer)
Registration (boost::weak_ptr< Observable< T > > observable, boost::weak_ptr< T > observer)
~Registration ()
void set (boost::shared_ptr< T > observer)
void set (boost::weak_ptr< T > observer)
Static Public Member Functions
static Ptr create (boost::weak_ptr< Observable< T > > observable, boost::shared_ptr< T > observer)
static Ptr create (boost::weak_ptr< Observable< T > > observable, boost::weak_ptr< T > observer)
Public Attributes
boost::weak_ptr< Observable< T > > observable
boost::shared_ptr< T > o
Reference to the observer (for non-weak registrations)
boost::weak_ptr< T > observer
Reference to the observer.
Detailed Description
template<typename T>
class Scroom::Utils::Detail::Registration< T >
Contain all info regarding the registration.
Performs de-registration on destruction
Definition at line 35 of file observable.hh.
Member Typedef Documentation
Ptr
template<typename T> typedef boost::shared_ptr<Registration> Scroom::Utils::Detail::Registration< T >::Ptr
Definition at line 42 of file observable.hh.
Constructor & Destructor Documentation
Registration() [1/3]
template<typename T > Scroom::Utils::Detail::Registration< T >::Registration ()
Definition at line 123 of file observable.hh.
       : observable(), o(), observer()
     {
     }
Registration() [2/3]
template<typename T> Scroom::Utils::Detail::Registration< T >::Registration (boost::weak_ptr< Observable< T > > observable, boost::shared_ptr< T > observer)
Definition at line 129 of file observable.hh.
       : observable(observable), o(observer), observer(observer)
     {
     }
Registration() [3/3]
template<typename T> Scroom::Utils::Detail::Registration< T >::Registration (boost::weak_ptr< Observable< T > > observable, boost::weak_ptr< T > observer)
Definition at line 135 of file observable.hh.
       : observable(observable), o(), observer(observer)
     {
       // We don't want to store a "hard" reference, so field o is intentionally empty.
     }
~Registration()
template<typename T > Scroom::Utils::Detail::Registration< T >::~Registration ()
Definition at line 171 of file observable.hh.
     {
     }
Member Function Documentation
create() [1/2]
template<typename T> Detail::Registration< T >::Ptr Scroom::Utils::Detail::Registration< T >::create (boost::weak_ptr< Observable< T > > observable, boost::shared_ptr< T > observer) static
Definition at line 157 of file observable.hh.
Referenced by Scroom::Utils::Observable< TileLoadingObserver >::registerObserver(), and Scroom::Utils::Observable< TileLoadingObserver >::registerStrongObserver().
     {
       return typename Detail::Registration<T>::Ptr(new Detail::Registration<T>(observable, observer));
     }
create() [2/2]
template<typename T> Detail::Registration< T >::Ptr Scroom::Utils::Detail::Registration< T >::create (boost::weak_ptr< Observable< T > > observable, boost::weak_ptr< T > observer) static
Definition at line 164 of file observable.hh.
     {
       return typename Detail::Registration<T>::Ptr(new Detail::Registration<T>(observable, observer));
     }
set() [1/2]
template<typename T> void Scroom::Utils::Detail::Registration< T >::set (boost::shared_ptr< T > observer)
Definition at line 142 of file observable.hh.
Referenced by Scroom::Utils::Observable< TileLoadingObserver >::registerObserver(), and Scroom::Utils::Observable< TileLoadingObserver >::registerStrongObserver().
     {
       this->o = observer;
       this->observer = observer;
     }
set() [2/2]
template<typename T> void Scroom::Utils::Detail::Registration< T >::set (boost::weak_ptr< T > observer)
Definition at line 149 of file observable.hh.
     {
       // We don't want to store a "hard" reference, so field o is intentionally empty.
       this->o.reset();
       this->observer = observer;
     }
Member Data Documentation
o
template<typename T> boost::shared_ptr<T> Scroom::Utils::Detail::Registration< T >::o
Reference to the observer (for non-weak registrations)
Definition at line 39 of file observable.hh.
Referenced by Scroom::Utils::Observable< TileLoadingObserver >::getObservers(), and Scroom::Utils::Detail::Registration< T >::set().
observable
template<typename T> boost::weak_ptr<Observable<T> > Scroom::Utils::Detail::Registration< T >::observable
Definition at line 38 of file observable.hh.
Referenced by Scroom::Utils::Detail::Registration< T >::create().
observer
template<typename T> boost::weak_ptr<T> Scroom::Utils::Detail::Registration< T >::observer
Reference to the observer.
Definition at line 40 of file observable.hh.
Referenced by Scroom::Utils::Detail::Registration< T >::set().
The documentation for this class was generated from the following file:
inc/scroom/observable.hh