Scroom: Scroom::Utils Namespace Reference
Scroom::Utils Namespace Reference
Namespaces
Detail
Classes
class Base
Base class that inherits from boost::enable_shared_from_this.
class Count
class Counted
class Counter
class Observable
Base class for something that accepts observers.
class Point
class ProgressInterfaceBroadcaster
class ProgressInterfaceFromProgressStateInterface
class ProgressInterfaceFromProgressStateInterfaceForwarder
class ProgressInterfaceMultiplexer
class ProgressStateInterface
Alternative interface used for reporting progress information.
class ProgressStateInterfaceFromProgressInterface
class ProgressStateInterfaceFromProgressInterfaceForwarder
class Rectangle
class Segment
class Timer
Typedefs
typedef boost::shared_ptr< void > Stuff
Stuff is a pointer to some private data.
typedef boost::weak_ptr< void > StuffWeak
typedef std::list< Stuff > StuffList
Functions
template<typename T >
bool isZero (T v)
template<>
bool isZero< int > (int v)
template<>
bool isZero< double > (double v)
template<typename T >
bool areEqual (T a, T b)
template<typename T >
Segment< T > make_segment (T start, T size)
template<typename T >
std::ostream & operator<< (std::ostream &os, const Segment< T > &s)
template<typename T >
Point< T > make_point (T x, T y)
template<typename T >
std::ostream & operator<< (std::ostream &os, const Point< T > &p)
template<typename T , typename U >
Point< typename std::common_type< T, U >::type > operator- (Point< T > left, Point< U > right)
template<typename T , typename U >
Point< typename std::common_type< T, U >::type > operator+ (Point< T > left, Point< U > right)
template<typename T >
Rectangle< T > make_rect (T x, T y, T width, T height)
template<typename T >
std::ostream & operator<< (std::ostream &os, const Rectangle< T > &r)
std::ostream & operator<< (std::ostream &os, const GdkRectangle &r)
template<typename T , typename U >
Rectangle< typename std::common_type< T, U >::type > operator* (Rectangle< T > left, U right)
template<typename T , typename U >
Rectangle< typename std::common_type< T, U >::type > operator* (T left, Rectangle< U > right)
Rectangle< double > operator* (GdkRectangle const &r, Point< double > const &p)
Rectangle< double > operator* (Point< double > const &p, GdkRectangle const &r)
template<typename T , typename U >
Rectangle< typename std::common_type< T, U >::type > operator- (Rectangle< T > left, Point< U > right)
Rectangle< int > roundOutward (Rectangle< double > r)
void dumpCounts ()
Typedef Documentation
Stuff
typedef boost::shared_ptr<void> Scroom::Utils::Stuff
Stuff is a pointer to some private data.
Definition at line 20 of file stuff.hh.
StuffList
typedef std::list<Stuff> Scroom::Utils::StuffList
Definition at line 22 of file stuff.hh.
StuffWeak
typedef boost::weak_ptr<void> Scroom::Utils::StuffWeak
Definition at line 21 of file stuff.hh.
Function Documentation
areEqual()
template<typename T > bool Scroom::Utils::areEqual (T a, T b)
Definition at line 37 of file linearsegment.hh.
Referenced by Scroom::Utils::Segment< value_type >::operator==().
     {
       return isZero(a-b);
     }
dumpCounts()
void Scroom::Utils::dumpCounts ()
Definition at line 18 of file counter.cc.
Referenced by Scroom::Utils::Base::shared_from_this().
 {
   Counter::instance()->dump();
 }
isZero()
template<typename T > bool Scroom::Utils::isZero (T v)
Referenced by areEqual(), and Scroom::Utils::Segment< value_type >::isEmpty().
isZero< double >()
template<> bool Scroom::Utils::isZero< double > (double v) inline
Definition at line 31 of file linearsegment.hh.
     {
       return std::abs(v) < 1e-6;
     }
isZero< int >()
template<> bool Scroom::Utils::isZero< int > (int v) inline
Definition at line 25 of file linearsegment.hh.
     {
       return v==0;
     }
make_point()
template<typename T > Point<T> Scroom::Utils::make_point (T x, T y)
Definition at line 84 of file point.hh.
Referenced by TransformationData::setAspectRatio().
     {
       return Point<T>(x,y);
     }
make_rect()
template<typename T > Rectangle<T> Scroom::Utils::make_rect (T x, T y, T width, T height)
Definition at line 327 of file rectangle.hh.
     {
       return Rectangle<T>(x, y, width, height);
     }
make_segment()
template<typename T > Segment<T> Scroom::Utils::make_segment (T start, T size)
Definition at line 206 of file linearsegment.hh.
     {
       return Segment<T>(start, size);
     }
operator*() [1/4]
template<typename T , typename U > Rectangle<typename std::common_type<T,U>::type> Scroom::Utils::operator* (Rectangle< T > left, U right)
Definition at line 350 of file rectangle.hh.
     {
       Rectangle<typename std::common_type<T,U>::type> result(left);
       result *= static_cast<typename std::common_type<T,U>::type>(right);
       return result;
     }
operator*() [2/4]
template<typename T , typename U > Rectangle<typename std::common_type<T,U>::type> Scroom::Utils::operator* (T left, Rectangle< U > right)
Definition at line 358 of file rectangle.hh.
     {
       return right*left;
     }
operator*() [3/4]
Rectangle<double> Scroom::Utils::operator* (GdkRectangle const & r, Point< double > const & p) inline
Definition at line 363 of file rectangle.hh.
     {
       return Rectangle<double>(r) * p;
     }
operator*() [4/4]
Rectangle<double> Scroom::Utils::operator* (Point< double > const & p, GdkRectangle const & r) inline
Definition at line 368 of file rectangle.hh.
     {
       return Rectangle<double>(r) * p;
     }
operator+()
template<typename T , typename U > Point<typename std::common_type<T,U>::type> Scroom::Utils::operator+ (Point< T > left, Point< U > right)
Definition at line 108 of file point.hh.
     {
       typedef typename std::common_type<T,U>::type R;
       Point<R> result(left);
       result += Point<R>(right);
       return result;
     }
operator-() [1/2]
template<typename T , typename U > Point<typename std::common_type<T,U>::type> Scroom::Utils::operator- (Point< T > left, Point< U > right)
Definition at line 98 of file point.hh.
     {
       typedef typename std::common_type<T,U>::type R;
       Point<R> result(left);
       result -= Point<R>(right);
       return result;
     }
operator-() [2/2]
template<typename T , typename U > Rectangle<typename std::common_type<T,U>::type> Scroom::Utils::operator- (Rectangle< T > left, Point< U > right)
Definition at line 374 of file rectangle.hh.
     {
       typedef typename std::common_type<T,U>::type R;
       return Rectangle<R>(left) - Point<R>(right);
     }
operator<<() [1/4]
template<typename T > std::ostream& Scroom::Utils::operator<< (std::ostream & os, const Point< T > & p)
Definition at line 90 of file point.hh.
     {
       return os << '(' << p.x
                 << ',' << p.y
                 << ')';
     }
operator<<() [2/4]
template<typename T > std::ostream& Scroom::Utils::operator<< (std::ostream & os, const Segment< T > & s)
Definition at line 212 of file linearsegment.hh.
     {
       return os << '(' << s.getStart()
                 << ',' << s.getSize()
                 << ')';
     }
operator<<() [3/4]
template<typename T > std::ostream& Scroom::Utils::operator<< (std::ostream & os, const Rectangle< T > & r)
Definition at line 333 of file rectangle.hh.
     {
       os << '<' << r.getLeft()
          << ',' << r.getTop()
          << ',' << r.getWidth()
          << ',' << r.getHeight()
          << '>';
       return os;
     }
operator<<() [4/4]
std::ostream& Scroom::Utils::operator<< (std::ostream & os, const GdkRectangle & r) inline
Definition at line 344 of file rectangle.hh.
     {
       return os << Rectangle<double>(r);
     }
roundOutward()
Rectangle<int> Scroom::Utils::roundOutward (Rectangle< double > r) inline
Definition at line 381 of file rectangle.hh.
Referenced by Operations1bpp::draw(), Operations8bpp::draw(), and Operations::draw().
     {
       int x = floor(r.getLeft());
       int y = floor(r.getTop());
       int width = ceil(r.getRight()) - x;
       int height = ceil(r.getBottom()) - y;
       return Rectangle<int>(x,y,width,height);
     }