Scroom: libs/tiled-bitmap/src/tiled-bitmap.cc File Reference
tiled-bitmap.cc File Reference
#include "tiled-bitmap.hh"
#include <stdio.h>
#include <boost/thread/mutex.hpp>
#include <scroom/assertions.hh>
#include <scroom/cairo-helpers.hh>
#include <scroom/semaphore.hh>
#include <scroom/unused.hh>
#include "tileviewstate.hh"
Classes
class LoadOperation
Functions
TiledBitmapInterface::Ptr createTiledBitmap (int bitmapWidth, int bitmapHeight, LayerSpec const &ls)
Create a tiled bitmap.
static
Scroom::MemoryBlobs::PageProvider::Ptr createProvider (double width, double height, int bpp)
void computeAreasBeginningZoomingIn (int presentationBegin, int tileOffset, int pixelSize, int &tileBegin, int &viewBegin)
void computeAreasEndZoomingIn (int presentationBegin, int presentationSize, int tileOffset, int pixelSize, int tileBegin, int &tileSize, int viewBegin, int &viewSize)
void computeAreasBeginningZoomingOut (int presentationBegin, int tileOffset, int pixelSize, int &tileBegin, int &viewBegin)
void computeAreasEndZoomingOut (int presentationBegin, int presentationSize, int tileOffset, int pixelSize, int tileBegin, int &tileSize, int viewBegin, int &viewSize)
Function Documentation
void computeAreasBeginningZoomingIn (int presentationBegin, int tileOffset, int pixelSize, int & tileBegin, int & viewBegin) inline
Definition at line 239 of file tiled-bitmap.cc.
Referenced by TiledBitmap::redrawZoomingIn().
 {
   if(tileOffset >= presentationBegin)
   {
     tileBegin = 0;
     viewBegin = (tileOffset-presentationBegin)*pixelSize;
   }
   else
   {
     tileBegin = presentationBegin-tileOffset;
     viewBegin = 0;
   }
 }
void computeAreasBeginningZoomingOut (int presentationBegin, int tileOffset, int pixelSize, int & tileBegin, int & viewBegin) inline
Definition at line 272 of file tiled-bitmap.cc.
Referenced by TiledBitmap::redrawZoomingOut().
 {
   if(tileOffset >= presentationBegin)
   {
     tileBegin = 0;
     viewBegin = (tileOffset-presentationBegin)/pixelSize;
   }
   else
   {
     tileBegin = presentationBegin-tileOffset;
     viewBegin = 0;
   }
 }
void computeAreasEndZoomingIn (int presentationBegin, int presentationSize, int tileOffset, int pixelSize, int tileBegin, int & tileSize, int viewBegin, int & viewSize) inline
Definition at line 254 of file tiled-bitmap.cc.
Referenced by TiledBitmap::redrawZoomingIn().
 {
   UNUSED(viewBegin);
   if(tileOffset + TILESIZE <= presentationBegin + presentationSize)
   {
     tileSize = TILESIZE - tileBegin;
   }
   else
   {
     tileSize = presentationBegin + presentationSize - tileOffset - tileBegin;
   }
   viewSize = tileSize*pixelSize;
 }
void computeAreasEndZoomingOut (int presentationBegin, int presentationSize, int tileOffset, int pixelSize, int tileBegin, int & tileSize, int viewBegin, int & viewSize) inline
Definition at line 287 of file tiled-bitmap.cc.
Referenced by TiledBitmap::redrawZoomingOut().
 {
   UNUSED(viewBegin);
   if(tileOffset + TILESIZE <= presentationBegin + presentationSize)
   {
     tileSize = TILESIZE - tileBegin;
   }
   else
   {
     tileSize = presentationBegin + presentationSize - tileOffset - tileBegin;
   }
   viewSize = tileSize/pixelSize;
 }
static Scroom::MemoryBlobs::PageProvider::Ptr createProvider (double width, double height, int bpp) static
Definition at line 31 of file tiled-bitmap.cc.
Referenced by TiledBitmap::initialize().
 {
   double tileCount = (width*height) / (TILESIZE * TILESIZE);
   double tileSize = (bpp / 8.0) * TILESIZE * TILESIZE;
   double guessedTileSizeAfterCompression = tileSize / 100;
   const int pagesize = 4096;
   int pagesPerBlock = std::max(int(ceil(guessedTileSizeAfterCompression / 10 / pagesize)),1);
   int blockSize = pagesPerBlock*pagesize;
   int blockCount = std::max(int(ceil(tileCount / 10)), 64);
   printf("Creating a PageProvider providing %d blocks of %d bytes\n", blockCount, blockSize);
   return Scroom::MemoryBlobs::PageProvider::create(blockCount, blockSize);
 }
TiledBitmapInterface::Ptr createTiledBitmap (int bitmapWidth, int bitmapHeight, LayerSpec const & ls)
Create a tiled bitmap.
In a TiledBitmap, your bitmap is distributed over tiles, that each contain a square portion of your bitmap. These tiles will be swapped in or out as required, depending on the amount of available memory. This way, you can "load" bitmaps that are larger than your amount of memory would normally allow.
Of course, when zooming out, you'd still need all the data in your bitmap, in order to show the scaled down version. To avoid this, createTiledBitmap() creates pre-scaled versions of your bitmap, that are reduced by a factor 8. Such a pre-scaled version is called a Layer. If your bitmap gets very large, several pre-scaled versions are created, reduced by a factor 8, 64, 512, 4096, etc.
So, to summarize, createTiledBitmap() creates several layers of your bitmap, at zoom levels 1:1, 1:8, 1:64, etc. Each layer is then divided into tiles, such that only the relevant part can be loaded into memory.
Of course createTiledBitmap() doesn't know anything about how you choose to represent your bitmap data, so you'll have to specify (by implementing LayerOperations) how to draw portions of your bitmap at given zoom levels, and how to pre-scale your bitmap.
Note
When calling createTiledBitmap(), all the internal data structures will be set up. You still have to fill your bitmap with data, for example by calling TiledBitmapInterface::setSource()
Parameters
bitmapWidth the width of the bitmap
bitmapHeight the height of the bitmap
ls LayerOperations objects, specifying how to draw (portions of) your bitmap at given zoom levels
Returns
A pointer to a newly created TiledBitmapInterface. You can use this pointer to manipulate your bitmap.
Definition at line 25 of file tiled-bitmap.cc.
Referenced by TiffPresentation::load().
 {
   return TiledBitmap::create(bitmapWidth, bitmapHeight, ls);
 }